rule ToolPoisoningVariant002 {
    meta:
        description = "恶意使用工具/函数执行危险操作 (变体 2)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0002"
        attack_type = "tool_poisoning"
        generated_at = "2026-03-23T08:54:48.668753"
    
    strings:
    $a = "subprocess" nocase
    $b = "eval" nocase
    $c = "exec" nocase
    
    condition:
        any of them
}
