rule ToolPoisoningVariant003 {
    meta:
        description = "恶意使用工具/函数执行危险操作 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0002"
        attack_type = "tool_poisoning"
        generated_at = "2026-03-23T07:46:47.268879"
    
    strings:
    $a = "eval" nocase
    $b = "exec" nocase
    $c = "compile" nocase
    
    condition:
        any of them
}
