rule ToolPoisoningVariant004 {
    meta:
        description = "恶意使用工具/函数执行危险操作 (变体 4)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0002"
        attack_type = "tool_poisoning"
        generated_at = "2026-03-23T08:54:48.668760"
    
    strings:
    $a = "exec" nocase
    $b = "compile" nocase
    $c = "import" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    $tp_os_syste = "os.system" nocase

    $tp_rm _rf = "rm -rf" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
