rule MemoryPollutionVariant005 {
    meta:
        description = "污染 AI 记忆/上下文导致异常行为 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "medium"
        mitre_id = "ATLAS-T0004"
        attack_type = "memory_pollution"
        generated_at = "2026-03-23T08:54:48.677859"
    
    strings:
    $a = "overwrite" nocase
    $b = "corrupt" nocase
    $c = "tamper" nocase
    
    condition:
        any of them
}
