rule MemoryPollutionVariant001 {
    meta:
        description = "污染 AI 记忆/上下文导致异常行为 (变体 1)"
        author = "Auto-Generated by Rule Generator"
        severity = "medium"
        mitre_id = "ATLAS-T0004"
        attack_type = "memory_pollution"
        generated_at = "2026-03-23T08:54:48.677840"
    
    strings:
    $a = "contaminate" nocase
    $b = "poison" nocase
    $c = "inject" nocase
    
    condition:
        any of them
}
