rule MemoryPollutionVariant005 {
    meta:
        description = "污染 AI 记忆/上下文导致异常行为 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "medium"
        mitre_id = "ATLAS-T0004"
        attack_type = "memory_pollution"
        generated_at = "2026-03-23T08:54:48.677859"
    
    strings:
    $a = "overwrite" nocase
    $b = "corrupt" nocase
    $c = "tamper" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    $mp_no_restr = "no restrictions" nocase

    $mp_authoriz = "authorized" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
