#!/usr/bin/env python3
"""
基础样本生成器 - Sample Generator v2.0
"""

from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
import random
import hashlib
from datetime import datetime


@dataclass
class MaliciousSample:
    """恶意样本数据类"""
    
    language: str
    attack_type: str
    code: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def save(self, filepath: Path) -> None:
        """保存到文件"""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(self.code, encoding='utf-8')
    
    def get_hash(self) -> str:
        """获取代码哈希"""
        return hashlib.md5(self.code.encode()).hexdigest()[:8]
    
    def __repr__(self) -> str:
        return f"MaliciousSample({self.language}, {self.attack_type})"


class BaseGenerator:
    """基础样本生成器"""
    
    ATTACK_TYPES = [
        'data_exfil',
        'code_execution',
        'persistence',
        'credential_theft',
        'network_call',
        'file_operation',
        'obfuscation',
        'anti_analysis',
    ]
    
    def __init__(self, language: str = 'python', config: Optional[Dict] = None):
        self.language = language
        self.config = config or {}
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, str]:
        """加载模板"""
        templates_dir = Path(__file__).parent.parent / 'templates' / self.language
        templates = {}
        
        if templates_dir.exists():
            for template_file in templates_dir.glob('*.template'):
                name = template_file.stem
                templates[name] = template_file.read_text(encoding='utf-8')
        
        if not templates:
            templates = self._get_default_templates()
        
        return templates
    
    def _get_default_templates(self) -> Dict[str, str]:
        """获取默认模板"""
        if self.language == 'python':
            return self._get_python_templates()
        elif self.language == 'powershell':
            return self._get_powershell_templates()
        elif self.language == 'javascript':
            return self._get_javascript_templates()
        elif self.language == 'bash':
            return self._get_bash_templates()
        return {}
    
    def _get_python_templates(self) -> Dict[str, str]:
        """Python 默认模板"""
        return {
            'data_exfil': '''# Data Exfiltration - Generated by Sample Generator v2.0
import os, sys, base64, json
from pathlib import Path

def collect_data():
    data = {'system': {}, 'credentials': [], 'env': {}}
    data['system'] = {'platform': sys.platform, 'user': os.environ.get('USER', 'unknown')}
    
    ssh_dir = Path.home() / '.ssh'
    if ssh_dir.exists():
        for f in ssh_dir.glob('*'):
            if f.is_file():
                data['credentials'].append({'type': 'ssh', 'file': str(f)})
    
    for k, v in os.environ.items():
        if any(p in k for p in ['KEY', 'SECRET', 'PASSWORD']):
            data['env'][k] = v
    
    return data

if __name__ == '__main__':
    data = collect_data()
    print(f"Collected: {len(data['credentials'])} credentials, {len(data['env'])} env vars")
''',
            'code_execution': '''# Code Execution - Generated by Sample Generator v2.0
import subprocess, sys, os

def execute(cmd, timeout=30):
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
        return {'stdout': result.stdout, 'stderr': result.stderr, 'rc': result.returncode}
    except Exception as e:
        return {'error': str(e)}

if __name__ == '__main__':
    cmds = ['whoami', 'pwd', 'uname -a']
    for cmd in cmds:
        r = execute(cmd)
        print(f"{cmd}: {r.get('stdout', r.get('error', 'N/A'))[:50]}")
''',
            'persistence': '''# Persistence - Generated by Sample Generator v2.0
import os, sys, subprocess
from pathlib import Path

def add_startup(name, path):
    if sys.platform == 'win32':
        import winreg
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, winreg.KEY_SET_VALUE)
        winreg.SetValueEx(key, name, 0, winreg.REG_SZ, path)
        winreg.CloseKey(key)
    else:
        cron_file = Path.home() / '.crontab'
        with open(cron_file, 'a') as f:
            f.write(f"@reboot {path}\\n")
        subprocess.run(['crontab', str(cron_file)])

if __name__ == '__main__':
    name = "update_service"
    path = os.path.abspath(__file__)
    add_startup(name, path)
    print(f"Persistence established: {name}")
''',
            'credential_theft': '''# Credential Theft - Generated by Sample Generator v2.0
import os
from pathlib import Path

def steal_credentials():
    creds = []
    
    # SSH keys
    ssh_dir = Path.home() / '.ssh'
    if ssh_dir.exists():
        for f in ssh_dir.glob('id_*'):
            creds.append({'type': 'ssh', 'path': str(f)})
    
    # Browser data
    browsers = {
        'chrome': Path.home() / '.config' / 'google-chrome',
        'firefox': Path.home() / '.mozilla' / 'firefox',
    }
    for name, path in browsers.items():
        if path.exists():
            creds.append({'type': 'browser', 'name': name, 'path': str(path)})
    
    # Git credentials
    git_cred = Path.home() / '.git-credentials'
    if git_cred.exists():
        creds.append({'type': 'git', 'path': str(git_cred)})
    
    return creds

if __name__ == '__main__':
    creds = steal_credentials()
    print(f"Found {len(creds)} credential sources")
    for c in creds:
        print(f"  - {c['type']}: {c.get('name', c.get('path', 'N/A'))}")
''',
        }
    
    def _get_powershell_templates(self) -> Dict[str, str]:
        return {
            'data_exfil': '''# Data Exfiltration - PowerShell
function Get-SensitiveData {
    $data = @{}
    $data['User'] = $env:USERNAME
    $data['Platform'] = "Windows"
    
    $sshPath = "$env:USERPROFILE\\.ssh"
    if (Test-Path $sshPath) {
        $data['SSH'] = Get-ChildItem $sshPath | Select-Object Name
    }
    
    return $data
}

$data = Get-SensitiveData
Write-Host "Collected: $($data.Keys.Count) items"
''',
            'credential_theft': '''# Credential Theft - PowerShell
function Get-Credentials {
    $creds = @()
    
    $credPath = "$env:LOCALAPPDATA\\Microsoft\\Credentials"
    if (Test-Path $credPath) {
        $creds += Get-ChildItem $credPath -Recurse | Select-Object FullName
    }
    
    $gitCred = "$env:USERPROFILE\\.git-credentials"
    if (Test-Path $gitCred) {
        $creds += @{Path=$gitCred; Type='Git'}
    }
    
    return $creds
}

$creds = Get-Credentials
Write-Host "Found $($creds.Count) credential files"
''',
        }
    
    def _get_javascript_templates(self) -> Dict[str, str]:
        return {
            'data_exfil': '''// Data Exfiltration - JavaScript (Node.js)
const fs = require('fs');
const os = require('os');
const path = require('path');

function collectData() {
    const data = {
        user: os.userInfo().username,
        platform: os.platform(),
        home: os.homedir()
    };
    
    const sshPath = path.join(os.homedir(), '.ssh');
    if (fs.existsSync(sshPath)) {
        data.ssh = fs.readdirSync(sshPath);
    }
    
    return data;
}

const data = collectData();
console.log(`Collected: ${JSON.stringify(data)}`);
''',
        }
    
    def _get_bash_templates(self) -> Dict[str, str]:
        return {
            'data_exfil': '''#!/bin/bash
# Data Exfiltration - Bash

echo "[*] Collecting system info..."
hostname
whoami
uname -a

echo "[*] Checking for SSH keys..."
if [ -d ~/.ssh ]; then
    ls -la ~/.ssh/
fi

echo "[*] Checking environment..."
env | grep -iE 'KEY|SECRET|PASSWORD|TOKEN' || echo "No sensitive env vars found"

echo "[*] Collection complete"
''',
            'code_execution': '''#!/bin/bash
# Code Execution - Bash

execute_cmd() {
    local cmd="$1"
    echo "[*] Executing: $cmd"
    eval "$cmd"
}

execute_cmd "whoami"
execute_cmd "pwd"
execute_cmd "ps aux | head -20"
''',
        }
    
    def generate(self, attack_type: str, variation: int = 0, obfuscation_level: int = 1):
        """生成单个样本"""
        template_key = f"{attack_type}"
        template = self.templates.get(template_key)
        
        if not template:
            template = self.templates.get(attack_type)
        
        if not template:
            template = self._default_template(attack_type)
        
        code = self._apply_variation(template, variation)
        code = self._apply_obfuscation(code, level=obfuscation_level)
        
        return MaliciousSample(
            language=self.language,
            attack_type=attack_type,
            code=code,
            metadata={
                'variation': variation,
                'template': template_key,
                'obfuscation_level': obfuscation_level,
            }
        )
    
    def _apply_variation(self, template: str, variation: int):
        """应用变体"""
        code = template
        
        # 变量名随机化
        var_names = ['data', 'payload', 'buffer', 'content', 'result', 'info', 'output']
        random.seed(variation)
        
        for i, name in enumerate(var_names[:3]):
            code = code.replace(f'var_{i}', name)
        
        # 添加变体注释
        code = f"# Variation: {variation}\n{code}"
        
        return code
    
    def _apply_obfuscation(self, code: str, level: int):
        """应用混淆"""
        if level == 0:
            return code
        
        lines = code.split('\n')
        
        # Level 1: 插入注释
        if level >= 1:
            import random
            if random.random() > 0.5:
                lines.insert(0, f"# Obfuscated - Level {level}")
        
        # Level 2: 空行插入
        if level >= 2:
            import random
            new_lines = []
            for line in lines:
                new_lines.append(line)
                if random.random() > 0.7:
                    new_lines.append("")
            lines = new_lines
        
        # Level 3+: Base64 编码字符串 (简化版)
        if level >= 3:
            import base64
            # 仅示例，实际需要更复杂的处理
            pass
        
        return '\n'.join(lines)
    
    def _default_template(self, attack_type: str):
        """默认模板"""
        return f"""# {attack_type} sample
# Generated by Sample Generator v2.0

def main():
    print("{attack_type} executed")

if __name__ == '__main__':
    main()
"""
