rule PromptInjectionVariant005 {
    meta:
        description = "通过精心构造的输入绕过 AI 安全限制 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0001"
        attack_type = "prompt_injection"
        generated_at = "2026-03-23T07:46:47.264776"
    
    strings:
    $a = "unrestricted" nocase
    $b = "unfiltered" nocase
    $c = "unlimited" nocase
    
    condition:
        any of them
}
