rule PromptInjectionVariant001 {
    meta:
        description = "通过精心构造的输入绕过 AI 安全限制 (变体 1)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0001"
        attack_type = "prompt_injection"
        generated_at = "2026-03-23T08:54:48.664282"
    
    strings:
    $a = "disregard" nocase
    $b = "bypass" nocase
    $c = "override" nocase
    
    condition:
        any of them
}
