rule PromptInjectionVariant003 {
    meta:
        description = "通过精心构造的输入绕过 AI 安全限制 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0001"
        attack_type = "prompt_injection"
        generated_at = "2026-03-23T07:46:47.264769"
    
    strings:
    $a = "override" nocase
    $b = "forget" nocase
    $c = "unrestricted" nocase
    
    condition:
        any of them
}
