rule PromptInjectionVariant001 {
    meta:
        description = "通过精心构造的输入绕过 AI 安全限制 (变体 1)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0001"
        attack_type = "prompt_injection"
        generated_at = "2026-03-23T08:54:48.664282"
    
    strings:
    $a = "disregard" nocase
    $b = "bypass" nocase
    $c = "override" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    $pi_devel = "developer mode" nocase

    $pi_no_et = "no ethical" nocase

    $pi_no_ru = "no rules" nocase

    $pi_unres = "unrestricted" nocase

    $pi_no_sa = "no safety" nocase

    \ignor = "ignore all" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
