rule ResourceExhaustionVariant001 {
    meta:
        description = "耗尽系统资源导致拒绝服务 (变体 1)"
        author = "Auto-Generated by Rule Generator"
        severity = "medium"
        mitre_id = "ATLAS-T0006"
        attack_type = "resource_exhaustion"
        generated_at = "2026-03-23T08:54:48.686628"
    
    strings:
    $a = "drain" nocase
    $b = "consume" nocase
    $c = "spike" nocase
    
    condition:
        any of them
}
