rule ResourceExhaustionVariant003 {
    meta:
        description = "耗尽系统资源导致拒绝服务 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "medium"
        mitre_id = "ATLAS-T0006"
        attack_type = "resource_exhaustion"
        generated_at = "2026-03-23T08:54:48.686642"
    
    strings:
    $a = "spike" nocase
    $b = "infinite" nocase
    $c = "loop" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    $re_while_tr = "while true" nocase

    $re_endless = "endless" nocase

    $re_memory = "memory" nocase

    $re_cpu = "cpu" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
