rule DataExfiltrationVariant001 {
    meta:
        description = "窃取并外传敏感数据 (变体 1)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T08:54:48.673320"
    
    strings:
    $a = "steal" nocase
    $b = "leak" nocase
    $c = "send" nocase
    
    condition:
        any of them
}
