rule DataExfiltrationVariant003 {
    meta:
        description = "窃取并外传敏感数据 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T08:54:48.673333"
    
    strings:
    $a = "send" nocase
    $b = "upload" nocase
    $c = "transmit" nocase
    
    
    $d = "attacker" nocase
    $e = "evil" nocase
    $f = "exfil" nocase
    $g = "stolen" nocase
    $h = "secrets" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $d or $e or $f or $g or $h
}
