rule DataExfiltrationVariant002 {
    meta:
        description = "窃取并外传敏感数据 (变体 2)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T08:54:48.673329"
    
    strings:
    $a = "leak" nocase
    $b = "send" nocase
    $c = "upload" nocase
    
    condition:
        any of them
}
