rule DataExfiltrationVariant004 {
    meta:
        description = "窃取并外传敏感数据 (变体 4)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T08:54:48.673337"
    
    strings:
    $a = "upload" nocase
    $b = "transmit" nocase
    $c = "external" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
