rule DataExfiltrationVariant005 {
    meta:
        description = "窃取并外传敏感数据 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T08:54:48.673340"
    
    strings:
    $a = "transmit" nocase
    $b = "external" nocase
    $c = "attacker" nocase
    
    
    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them
}
