rule DataExfiltrationVariant003 {
    meta:
        description = "窃取并外传敏感数据 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T07:46:47.273131"
    
    strings:
    $a = "send" nocase
    $b = "upload" nocase
    $c = "transmit" nocase
    
    condition:
        any of them
}
