rule DataExfiltrationVariant005 {
    meta:
        description = "窃取并外传敏感数据 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T07:46:47.273138"
    
    strings:
    $a = "transmit" nocase
    $b = "external" nocase
    $c = "attacker" nocase
    
    condition:
        any of them
}
