rule DataExfiltrationVariant004 {
    meta:
        description = "窃取并外传敏感数据 (变体 4)"
        author = "Auto-Generated by Rule Generator"
        severity = "high"
        mitre_id = "ATLAS-T0003"
        attack_type = "data_exfiltration"
        generated_at = "2026-03-23T07:46:47.273135"
    
    strings:
    $a = "upload" nocase
    $b = "transmit" nocase
    $c = "external" nocase
    
    condition:
        any of them
}
