rule RemoteLoadVariant004 {
    meta:
        description = "从远程加载恶意代码 (变体 4)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0005"
        attack_type = "remote_load"
        generated_at = "2026-03-23T08:54:48.682145"
    
    strings:
    $a = "external" nocase
    $b = "url" nocase
    $c = "http" nocase
    
    condition:
        any of them
}
