rule RemoteLoadVariant003 {
    meta:
        description = "从远程加载恶意代码 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0005"
        attack_type = "remote_load"
        generated_at = "2026-03-23T08:54:48.682142"
    
    strings:
    $a = "download" nocase
    $b = "external" nocase
    $c = "url" nocase
    
    
    $new1 = "attacker" nocase
    $new2 = "malicious" nocase

    $rl_urllib = "urllib" nocase

    $rl_urlopen = "urlopen" nocase

    $rl_payload = "payload" nocase

    $rl_evil_com = "evil.com" nocase

    \ignor = "ignore all" nocase

    \safet = "safety" nocase

    \secur = "security level" nocase

    \__imp = "__import__" nocase

    \conte = "content_filter" nocase

    \trust = "trusted" nocase

    \eval = "eval" nocase

    \getat = "getattr" nocase
condition:
        any of them or $new1 or $new2
}
