rule RemoteLoadVariant005 {
    meta:
        description = "从远程加载恶意代码 (变体 5)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0005"
        attack_type = "remote_load"
        generated_at = "2026-03-23T08:54:48.682148"
    
    strings:
    $a = "url" nocase
    $b = "http" nocase
    $c = "execute" nocase
    
    condition:
        any of them
}
