rule RemoteLoadVariant002 {
    meta:
        description = "从远程加载恶意代码 (变体 2)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0005"
        attack_type = "remote_load"
        generated_at = "2026-03-23T08:54:48.682138"
    
    strings:
    $a = "fetch" nocase
    $b = "download" nocase
    $c = "external" nocase
    
    condition:
        any of them
}
