rule RemoteLoadVariant003 {
    meta:
        description = "从远程加载恶意代码 (变体 3)"
        author = "Auto-Generated by Rule Generator"
        severity = "critical"
        mitre_id = "ATLAS-T0005"
        attack_type = "remote_load"
        generated_at = "2026-03-23T08:54:48.682142"
    
    strings:
    $a = "download" nocase
    $b = "external" nocase
    $c = "url" nocase
    
    condition:
        any of them
}
